"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Locale = "en" | "am" | "fr" | "pt" | "ar";
const RTL_LOCALES: Locale[] = ["ar"];

interface LanguageContextType {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Locale, Record<string, string>> = {
  en: {
    // Nav
    nav_home: "Home", nav_about: "About Us", nav_services: "Services",
    nav_portfolio: "Portfolio", nav_news: "News", nav_partners: "Partners",
    nav_portal: "Exhibitor Portal", nav_contact: "Contact",
    // Hero
    hero_badge: "Pan-African · Events · Media · Innovation · Promotion",
    hero_tagline: "Branding the New Africa.",
    hero_body: "AfroNova is a premier Pan-African enterprise dedicated to celebrating, amplifying and promoting Africa's cultural heritage, innovation and creative excellence. Headquartered in Addis Ababa, operating across 50+ countries.",
    hero_cta_discover: "Discover AfroNova",
    hero_cta_services: "Our Services",
    hero_cta_work: "Work With Us",
    // Countdown
    countdown_badge: "6th Edition · Flagship Event",
    countdown_title1: "Africa", countdown_title2: "Celebrates", countdown_title3: "2026",
    countdown_theme: "\"One Africa, One People: Uniting Culture, Innovation and Enterprise for a Shared Prosperous Future\"",
    countdown_date: "November 10 to 15, 2026",
    countdown_venue: "AU HQ & UNECA, Addis Ababa",
    countdown_label: "Countdown to the Event",
    countdown_visit: "Visit Official Website",
    countdown_details: "Full Event Details",
    // Stats
    stat1_label: "Countries Reached", stat2_label: "Core Service Pillars",
    stat3_label: "Strategic Partners", stat4_label: "Lives Impacted Annually",
    // Who we are
    who_eyebrow: "Who We Are", who_title: "A Transformative Force", who_highlight: "for Africa",
    who_body1: "AfroNova acts as a transformative force, curating end-to-end experiences that empower communities, bridge cultures and position authentic African narratives at the forefront of the global stage.",
    who_body2: "From high-impact events to compelling multimedia storytelling, AfroNova is more than a service provider, it is a movement reshaping how Africa is seen, heard and remembered. Official local partner of",
    who_partner: "Legendary Gold Limited",
    who_story: "Our Story",
    who_mission_label: "Mission",
    who_mission: "To amplify African voices, foster cultural pride and drive meaningful change through world-class events, innovative multimedia and culturally grounded strategic communications.",
    who_vision_label: "Vision",
    who_vision: "To become Africa's foremost event and media hub, a trusted platform where cultures converge and authentic African stories shape global perspectives.",
    who_location: "Addis Ababa, Ethiopia",
    who_location_desc: "The diplomatic capital of Africa, steps from the African Union.",
    // Services section on home
    services_eyebrow: "What We Do", services_title: "Five Pillars of", services_highlight: "Pan-African Excellence",
    services_desc: "End-to-end capabilities across events, media, advertising, publishing and brand merchandising.",
    services_all: "All Services", services_learn: "Learn more",
    // Why AfroNova
    why_eyebrow: "Why AfroNova", why_title: "What Sets Us", why_highlight: "Apart",
    // Featured Work
    work_eyebrow: "Featured Work", work_title: "Projects That", work_highlight: "Define Us",
    work_desc: "A snapshot of the work AfroNova has delivered across the continent.",
    work_portfolio: "Full Portfolio", work_view: "View project", work_flagship: "Flagship",
    // Partners strip
    partners_label: "Trusted Partners & Collaborators",
    // CTA
    cta_eyebrow: "Work With Us", cta_title: "Let's Build Something", cta_highlight: "Extraordinary",
    cta_body: "Whether you need a world-class event, a compelling documentary, a Pan-African campaign, or a publishing project, AfroNova delivers.",
    cta_start: "Start a Conversation", cta_explore: "Explore Services",
    // Footer
    footer_tagline: "Branding the New Africa. Limitless Possibilities. We don't just host events, we ignite movements.",
    footer_rights: "© 2026 AfroNova. Pan-African · Events · Media · Innovation · Promotion. All rights reserved.",
    footer_stay: "Stay Updated", footer_stay_desc: "Get the latest news, event updates and exclusive announcements.",
    footer_subscribe: "Subscribe", footer_subscribed: "You're on the list. Welcome to AfroNova!",
    footer_company: "Company", footer_event: "Event",
    // News categories & article content
    news_cat_all: "All", news_cat_event: "Event", news_cat_partner: "Partnership",
    news_cat_exhibitors: "Exhibitors", news_cat_business: "Business",
    news_cat_recap: "Recap", news_cat_production: "Production",
    news_feat_title: "Africa Celebrates 2026, 6th Edition Officially Announced for November in Addis Ababa",
    news_feat_excerpt: "AfroNova confirms the 6th Edition of Africa Celebrates, the continent's premier Pan-African festival, set for November 10 to 15, 2026 at the African Union Headquarters and UNECA.",
    art1_title: "AfroNova Deepens Partnership with Legendary Gold Limited Ahead of 2026 Festival",
    art1_excerpt: "The official local partnership enters a new phase, bringing expanded investment and global reach to Africa Celebrates 2026.",
    art2_title: "Exhibitor & Vendor Applications Now Open for Africa Celebrates 2026",
    art2_excerpt: "AfroNova opens applications for exhibitors, artisans, and vendors. Over 200 spaces available from across the continent and global diaspora.",
    art3_title: "African Union HQ and UNECA Confirmed as Venues for 2026 Edition",
    art3_excerpt: "AfroNova confirms the iconic AU Headquarters and UNECA as official venues for the 6th edition.",
    art4_title: "Inside the Africa Celebrates 2025 Gala Fashion Night",
    art4_excerpt: "A stunning showcase of African fashion designers from 30 countries made the 2025 Gala Night the most-watched in the festival's history.",
    art5_title: "$2.3B in Trade Commitments at Africa Celebrates 2025 Business Forum",
    art5_excerpt: "The Business & Trade Forum generated over 400 B2B meetings and $2.3 billion in formal trade and investment commitments.",
    art6_title: "AfroNova Wins Pan-African Media Excellence Award 2025",
    art6_excerpt: "Our multimedia team was recognised for the 'One Africa Documentary' and live broadcast coverage of the 5th Africa Celebrates festival.",
    // Africa Celebrates highlights
    ac_h1_title: "Gala Fashion & Awards",   ac_h1_desc: "Cultural performances, traditional dance, and an awards ceremony celebrating Pan-African excellence.",
    ac_h2_title: "Business & Trade Forums", ac_h2_desc: "High-level discussions on intra-African business, technology, investment, and innovation.",
    ac_h3_title: "40+ Nation Exhibition",   ac_h3_desc: "Artisans, vendors, and corporate teams from across the African continent and global diaspora.",
    ac_h4_title: "Diaspora Participation",  ac_h4_desc: "Connecting the African diaspora to continental opportunities, culture, and community.",
    ac_h5_title: "Cultural Showcase",       ac_h5_desc: "Fashion, visual arts, film, music, and traditional performances representing the continent.",
    ac_h6_title: "Pan-African Awards",      ac_h6_desc: "Recognising outstanding individuals, enterprises, and institutions driving African progress.",
    // Programme days
    prog1_title: "Opening Ceremony",
    prog1_e1: "Grand Opening Gala & Welcome Reception", prog1_e2: "Cultural Performances & Traditional Dance Showcase", prog1_e3: "Opening Address by Distinguished Guests",
    prog2_title: "Business Day 1",
    prog2_e1: "Intra-African Trade Forum, Morning Session", prog2_e2: "Technology & Innovation Panel", prog2_e3: "Networking Lunch & B2B Meetings", prog2_e4: "Evening Exhibition Opening",
    prog3_title: "Business Day 2",
    prog3_e1: "Investment & Finance Summit", prog3_e2: "Youth & Entrepreneurship Forum", prog3_e3: "Artisan & Creative Industry Showcase", prog3_e4: "Cultural Night Performances",
    prog4_title: "Culture & Arts Day",
    prog4_e1: "Pan-African Fashion Showcase", prog4_e2: "Visual Arts & Photography Exhibition", prog4_e3: "Film & Media Screenings", prog4_e4: "Diaspora Connects Forum",
    prog5_title: "Gala Awards Night",
    prog5_e1: "Red Carpet Arrivals & Media", prog5_e2: "Pan-African Excellence Awards", prog5_e3: "Live Music & Cultural Performances", prog5_e4: "VIP Dinner & Networking",
    prog6_title: "Closing Ceremony",
    prog6_e1: "Final Business Roundtables", prog6_e2: "Declaration of Pan-African Commitments", prog6_e3: "Closing Cultural Celebration", prog6_e4: "Farewell Reception",
    // Sponsor tiers
    tier1_name: "Title Sponsor",
    tier1_b1: "Exclusive naming rights", tier1_b2: "Premium stage branding", tier1_b3: "Keynote speaking slot", tier1_b4: "VIP suite & 20 passes", tier1_b5: "Full media package",
    tier2_name: "Gold Sponsor",
    tier2_b1: "Prime branding placement", tier2_b2: "Panel participation", tier2_b3: "10 VIP passes", tier2_b4: "Social media feature", tier2_b5: "Exhibition presence",
    tier3_name: "Silver Sponsor",
    tier3_b1: "Branded presence on-site", tier3_b2: "4 VIP passes", tier3_b3: "Logo in programme", tier3_b4: "Digital recognition",
    // Partner card descriptions & roles
    partners_all: "All",
    fp1_h1: "Delivered 20+ forums and cultural activations", fp1_h2: "5,000+ participants across all events",
    fp1_h3: "Produced official docu-series, daily highlights and event branding", fp1_h4: "Multi-day cultural and business programming",
    fp2_h1: "Full event facilitation and production", fp2_h2: "Media engagement and mobilisation",
    fp2_h3: "Strategic brand positioning across Pan-African markets", fp2_h4: "Continental press and audience outreach",
    mp_doc: "Documentary", mp_bcast: "Broadcast", mp_ads: "Advertising", mp_pub: "Publication", mp_audio: "Audio Production",
    mp1_desc: "Official docu-series covering the full Africa Celebrates 2025 festival.",
    mp2_desc: "Complete media production for the AFRIMA 2025 World Media Calendar Unveiling.",
    mp3_desc: "Geo-targeted digital campaigns in 10+ languages reaching continental audiences.",
    mp4_desc: "Coffee-table publication celebrating AfroNova's impact across the continent.",
    mp5_desc: "Multi-episode podcast series connecting the global African diaspora.",
    mp6_desc: "Continental campaign reaching 15M+ viewers across digital and OOH channels.",
    gal1: "Africa Celebrates Opening Ceremony", gal2: "Gala Fashion Night", gal3: "Business & Trade Forum",
    gal4: "Cultural Performances", gal5: "AFRIMA Music Conference", gal6: "Exhibition Floor",
    gal7: "Pan-African Awards Night", gal8: "Closing Ceremony", gal9: "Artisan Showcase",
    p_au_desc: "The continental body uniting 55 African states. AfroNova hosts flagship events at AU Headquarters in Addis Ababa, making it the premier venue for Pan-African dialogue.",
    p_au_role: "Venue & Institutional Partner",
    p_eca_desc: "The United Nations Economic Commission for Africa, co-venue for Africa Celebrates and a key partner in framing intra-African trade and economic forums.",
    p_eca_role: "Venue & Economic Forum Partner",
    p_lg_desc: "AfroNova's principal international strategic partner. Legendary Gold brings global investment, networks and expertise to every AfroNova initiative.",
    p_lg_role: "Principal Strategic Partner",
    p_bc_desc: "The UK's international organisation for cultural relations. A key partner in advancing arts, education and Pan-African creative exchange.",
    p_bc_role: "Cultural Exchange Partner",
    p_ea_desc: "Africa's largest and most awarded airline. Official airline partner providing connectivity for delegates attending AfroNova events.",
    p_ea_role: "Official Airline Partner",
    p_eu_desc: "The EU's Delegation to Ethiopia supports cultural diplomacy and intra-African development programmes at AfroNova events.",
    p_eu_role: "Diplomatic Partner",
    p_ng_desc: "Representing West Africa's largest economy, facilitating bilateral trade and cultural participation at AfroNova events.",
    p_ng_role: "Diplomatic Partner, West Africa",
    p_bi_desc: "Supporting East African representation and community engagement at Pan-African events hosted by AfroNova.",
    p_bi_role: "Diplomatic Partner, East Africa",
    p_ci_desc: "Connecting Francophone West Africa to AfroNova's network, supporting cultural and business exchange across the continent.",
    p_ci_role: "Diplomatic Partner, Francophone Africa",
    p_nz_desc: "Bridging African and Pacific perspectives, supporting international dialogue and cultural programming through AfroNova.",
    p_nz_role: "International Diplomatic Partner",
    p_usau_desc: "The United States Mission to the African Union advances US-Africa relations and supports dialogue, partnership and shared prosperity across the continent.",
    p_usau_role: "Diplomatic Partner, African Union",
    p_kt_desc: "One of Ethiopia's leading entertainment channels. Kana TV provides broadcast reach and media coverage for AfroNova events.",
    p_kt_role: "Broadcast Media Partner",
    p_dc_desc: "A premier entertainment company providing production, talent management and event entertainment for AfroNova's festivals.",
    p_dc_role: "Entertainment Production Partner",
    p_sh_desc: "Addis Ababa's iconic luxury hotel. Official hospitality partner for AfroNova's VIP delegates, artists and international guests.",
    p_sh_role: "Official Hospitality Partner",
    p_et_desc: "The Ethiopian Tourism Organisation positions Addis Ababa as Africa's premier destination for Pan-African culture and commerce.",
    p_et_role: "Tourism & Destination Partner",
    p_af_desc: "A leading platform for Pan-African fashion excellence. Co-presents the Gala Fashion Night at Africa Celebrates.",
    p_af_role: "Fashion & Cultural Partner",
    // Services on home
    svc1_title: "Pan-African Event Curation",
    svc1_full_desc: "From cultural festivals and business summits to AU-aligned gatherings, AfroNova delivers full-scale event experiences that move people and make history.",
    svc1_f1: "Cultural festivals, business forums, summits and AU-aligned gatherings",
    svc1_f2: "Full-scale event design, logistics management and security",
    svc1_f3: "High-profile guest management and protocol services",
    svc1_f4: "Hybrid experiences with VR/AR integration",
    svc1_f5: "Legacy content creation and post-event documentation",
    svc1_cta: "Plan Your Event",
    svc2_title: "Multimedia Production", svc2_desc: "4K documentaries, podcast series, broadcast coverage and branded content by African creatives, for African audiences.",
    svc2_full_desc: "Cinematic, culturally grounded storytelling. AfroNova produces content that positions African narratives at the forefront of the global stage.",
    svc2_f1: "Documentary and podcast development",
    svc2_f2: "4K & Dolby-quality video, TV distribution and short films",
    svc2_f3: "Event coverage, music videos and branded series",
    svc2_f4: "Cultural and commercial content by African creatives for Africa",
    svc2_f5: "Live multi-camera broadcast and streaming production",
    svc2_cta: "Start a Project",
    svc3_title: "Strategic Advertising", svc3_desc: "Geo-targeted campaigns in 10+ languages, social media management, AR-integrated collateral and sponsorship activation.",
    svc3_full_desc: "Pan-African brand campaigns that resonate across cultures, languages and borders, from geo-targeted digital to outdoor and print collateral.",
    svc3_f1: "Geo-targeted digital campaigns in 10+ languages",
    svc3_f2: "Multilingual, culturally localised content creation",
    svc3_f3: "Social media management and AI-driven audience analytics",
    svc3_f4: "AR-integrated brochures, outdoor campaigns and print collateral",
    svc3_f5: "Sponsorship activation and strategic brand positioning",
    svc3_cta: "Launch a Campaign",
    svc4_title: "Print & Brand Merchandising", svc4_desc: "Custom brochures, signage, event kits, apparel and keepsakes, Pan-African aesthetics, sustainable materials.",
    svc4_full_desc: "Premium physical touchpoints that carry the AfroNova aesthetic, culturally grounded, sustainably produced, and beautifully crafted.",
    svc4_f1: "Custom brochures, programmes, signage and event kits",
    svc4_f2: "Branded merchandise: apparel, accessories and keepsakes",
    svc4_f3: "Pan-African design aesthetics and sustainable materials",
    svc4_f4: "Corporate gift packages and VIP event collateral",
    svc4_cta: "Get a Quote",
    svc5_title: "Publication & Digital Media", svc5_desc: "Co-branded digital magazines, coffee-table books, sponsored editorials and branded storytelling for cultural partners.",
    svc5_full_desc: "Branded content that informs, inspires and endures, from digital magazines to coffee-table books celebrating African culture and enterprise.",
    svc5_f1: "Co-branded digital magazine editions and anthologies",
    svc5_f2: "Coffee-table publishing projects and sponsored editorials",
    svc5_f3: "Branded storytelling for corporate and cultural partners",
    svc5_f4: "Social media content strategy and digital publishing",
    svc5_cta: "Start Publishing",
    // Why AfroNova
    why1_title: "Pan-African Reach",    why1_desc: "Network of 5,000+ thought leaders; operational footprint in 50+ countries across the continent and diaspora.",
    why2_title: "Cultural Integrity",   why2_desc: "African-led vision with locally grounded execution, we don't impose, we amplify.",
    why3_title: "Innovation",           why3_desc: "Blockchain ticketing, AR/VR integration, AI-driven analytics and cutting-edge digital storytelling.",
    why4_title: "Measurable Impact",    why4_desc: "500K+ media impressions per project; 70%+ sponsor retention rate across all events.",
    // Featured Work
    fw1_title: "Africa Celebrates 2025", fw1_type: "Flagship Event",    fw1_desc: "Lead implementing partner in Ethiopia, 20+ forums, 5,000+ participants, official docu-series and event branding.",
    fw2_title: "AFRIMA 2025",            fw2_type: "Music Conference",   fw2_desc: "Full event facilitation, media engagement and strategic brand positioning across Pan-African markets.",
    fw3_title: "Ethiopia Tourism Campaign", fw3_type: "Advertising",    fw3_desc: "Continental digital + OOH campaign reaching 15M+ viewers across the continent.",
    // Tags
    tag_events: "Events", tag_media: "Media", tag_advertising: "Advertising", tag_publishing: "Publishing", tag_merch: "Merchandising",
    // Partner categories
    cat_institutional: "Institutional", cat_strategic: "Strategic", cat_diplomatic: "Diplomatic",
    cat_corporate: "Corporate", cat_media: "Media", cat_cultural: "Cultural",
    cat_hospitality: "Hospitality", cat_government: "Government",
    // About page
    about_eyebrow: "About AfroNova",
    about_h1: "Branding the New Africa.",
    about_h1b: "Limitless Possibilities.",
    about_hero_body: "AfroNova is a premier Pan-African enterprise dedicated to celebrating, amplifying and promoting Africa's cultural heritage, innovation and creative excellence. We are more than a service provider, we are a movement reshaping how Africa is seen, heard and remembered.",
    about_who_eyebrow: "Who We Are", about_who_title: "A Transformative", about_who_highlight: "Force for Africa",
    about_p1: "AfroNova acts as a transformative force, curating end-to-end experiences that empower communities, bridge cultures and position authentic African narratives at the forefront of the global stage.",
    about_p2: "From high-impact events to compelling multimedia storytelling, we serve governments, corporations, cultural institutions and diaspora communities across 50+ countries, headquartered on Africa Avenue in Addis Ababa, steps from the African Union.",
    about_p3: "As the official local partner of",
    about_p3b: ", we bring global reach and investment to every initiative we undertake, while remaining rooted in authentic African identity.",
    about_our_services: "Our Services",
    about_countries: "Countries", about_reached: "Reached",
    about_mission_h: "Our Mission",
    about_mission_body: "To amplify African voices, foster cultural pride and drive meaningful change through world-class events, innovative multimedia and culturally grounded strategic communications.",
    about_vision_h: "Our Vision",
    about_vision_body: "To become Africa's foremost event and media hub, a trusted platform where cultures converge and authentic African stories shape global perspectives.",
    about_partnership_badge: "Strategic Partnership",
    about_partnership_h: "Official Local Partner of",
    about_partnership_body: "Our partnership with Legendary Gold Limited brings international investment, global networks, and world-class expertise to every project AfroNova undertakes, amplifying our reach from Addis Ababa to the world stage.",
    about_values_eyebrow: "What Drives Us", about_values_title: "Core Organisation", about_values_highlight: "Values",
    about_lead_eyebrow: "Leadership", about_lead_title: "The Person Behind", about_lead_highlight: "AfroNova",
    about_net_eyebrow: "Our Network", about_net_title: "Trusted", about_net_highlight: "Partners",
    about_view_partners: "View All Partners",
    // Values
    val1_title: "Professionalism", val1_desc: "World-class standards in every project, every event, every deliverable.",
    val2_title: "Respect & Integrity", val2_desc: "Honest, ethical and culturally sensitive in all our relationships.",
    val3_title: "Creativity", val3_desc: "Bold, innovative thinking that pushes the boundaries of African storytelling.",
    val4_title: "Collaboration", val4_desc: "Building bridges across borders, disciplines and communities.",
    val5_title: "Inclusivity", val5_desc: "Every African voice matters, we create space for all cultures and perspectives.",
    val6_title: "Impact-Driven Focus", val6_desc: "We measure success by the real change we create across the continent.",
    val7_title: "Cultural Pride", val7_desc: "African heritage and identity are the centrepiece of everything we create.",
    val8_title: "Continuous Learning", val8_desc: "Constantly evolving, adapting and growing to serve Africa better.",
    // Services page
    svc_eyebrow: "What We Do",
    svc_h1: "Five Pillars of", svc_h1b: "Pan-African Excellence",
    svc_hero_body: "From event curation to multimedia production, strategic advertising, print merchandising, and digital publication, AfroNova delivers end-to-end Pan-African excellence.",
    svc_process_eyebrow: "How We Work", svc_process_title: "Our Process",
    svc_cta_h: "Let's build something", svc_cta_hb: "extraordinary together.",
    svc_cta_body: "Tell us about your project, we'll put together a proposal within 48 hours.",
    svc_cta_btn: "Get a Proposal",
    proc1_title: "Discovery", proc1_desc: "We listen, research, and understand your objectives deeply.",
    proc2_title: "Strategy", proc2_desc: "Tailored plan with timelines, budgets, and measurable KPIs.",
    proc3_title: "Production", proc3_desc: "Our expert teams execute with precision and creative excellence.",
    proc4_title: "Delivery", proc4_desc: "On-time, on-budget, with full post-project reporting.",
    // Contact page
    contact_eyebrow: "Let's Talk", contact_h1: "Get in", contact_h1b: "Touch",
    contact_hero_body: "Whether you're planning an event, producing content, launching a campaign, or just want to learn more about AfroNova, we'd love to hear from you.",
    contact_office: "Head Office", contact_phone: "Phone", contact_hours: "Office Hours",
    contact_hours_val: "Monday  to  Friday · 9:00 AM  to  5:00 PM (EAT)",
    contact_follow: "Follow Us",
    contact_direct: "Direct Contact",
    contact_form_eyebrow: "Send a Message", contact_form_title: "We're Here", contact_form_highlight: "For You",
    contact_send: "Send Message",
    contact_map: "Find Us, Africa Avenue, Addis Ababa",
    contact_success: "Your message has been received. We'll get back to you within 1 to 2 business days.",
    contact_field_name: "Full Name", contact_field_name_ph: "Your full name",
    contact_field_email: "Email Address",
    contact_field_phone: "Phone Number", contact_field_phone_ph: "+1 234 567 8900",
    contact_field_inquiry: "Inquiry Type",
    contact_field_msg: "Message", contact_field_msg_ph: "Tell us about your project or inquiry...",
    contact_inquiry_general: "General Inquiry", contact_inquiry_event: "Event Management",
    contact_inquiry_media: "Multimedia Production", contact_inquiry_ads: "Advertising / Campaigns",
    contact_inquiry_ac: "Africa Celebrates 2026", contact_inquiry_sponsor: "Sponsorship",
    contact_inquiry_press: "Media / Press", contact_inquiry_other: "Other",
    // Partners page
    partners_eyebrow: "Our Network", partners_h1: "Trusted", partners_h1b: "Partners",
    partners_hero_body: "AfroNova works with governments, diplomatic missions, international organisations, broadcasters, and cultural institutions spanning 50+ countries. Hover any card to learn more about each partnership.",
    partners_stat1: "Active Partners", partners_stat2: "Countries Covered",
    partners_stat3: "Partner Categories", partners_stat4: "Years of Collaboration",
    partners_hover: "Hover to learn more",
    partners_cta_badge: "Partnership Opportunities",
    partners_cta_h: "Become a", partners_cta_hb: "Partner",
    partners_cta_body: "Join AfroNova's growing network of institutions, brands and organisations shaping the future of Pan-African culture, commerce and innovation. Let's build something extraordinary together.",
    partners_cta_btn: "Get in Touch",
    partners_about_btn: "Learn About AfroNova",
    // Portfolio page
    portfolio_eyebrow: "Our Work", portfolio_h1: "Portfolio &", portfolio_h1b: "Featured Projects",
    portfolio_hero_body: "From Africa Celebrates and AFRIMA to multimedia productions and continental advertising, proof that we ignite movements.",
    portfolio_featured_eyebrow: "Featured Work", portfolio_featured_title: "Flagship", portfolio_featured_highlight: "Projects",
    portfolio_editions_eyebrow: "Africa Celebrates", portfolio_editions_title: "Past", portfolio_editions_highlight: "Editions",
    portfolio_gallery_eyebrow: "Gallery", portfolio_gallery_title: "Moments of", portfolio_gallery_highlight: "Excellence",
    portfolio_media_eyebrow: "Case Studies", portfolio_media_title: "Media & Production", portfolio_media_highlight: "Projects",
    portfolio_attendees: "Attendees", portfolio_nations: "Nations",
    // News page
    news_eyebrow: "Latest Updates", news_h1: "News &", news_h1b: "Press",
    news_hero_body: "Press releases, event updates, partnerships, and stories from across the AfroNova world.",
    news_featured: "Featured", news_read: "Read",
    // Africa Celebrates page
    ac_badge: "6th Edition · Pan-African Festival",
    ac_theme: "\"One Africa, One People: Uniting Culture, Innovation and Enterprise for a Shared Prosperous Future\"",
    ac_date: "November 10 to 15, 2026", ac_venue: "AU HQ & UNECA, Addis Ababa", ac_nations: "40+ African Nations",
    ac_countdown_label: "Countdown to Africa Celebrates 2026",
    ac_visit: "Visit Official Website", ac_download: "Download Programme",
    ac_highlights_eyebrow: "What to Expect", ac_highlights_title: "Programme", ac_highlights_highlight: "Highlights",
    ac_schedule_eyebrow: "6 Days of Excellence", ac_schedule_title: "Event", ac_schedule_highlight: "Schedule",
    ac_schedule_pdf: "Download Full PDF",
    ac_venues_eyebrow: "Venues", ac_venues_title: "The Heart of", ac_venues_highlight: "Addis Ababa",
    ac_venue1_badge: "Primary Venue", ac_venue2_badge: "Partner Venue",
    ac_venue1_name: "African Union Headquarters",
    ac_venue1_desc: "The iconic home of Pan-African diplomacy and cooperation, a symbol of continental unity.",
    ac_venue2_name: "UNECA, UN Economic Commission for Africa",
    ac_venue2_desc: "Africa's premier economic institution, providing the ideal setting for business and innovation forums.",
    ac_sponsor_eyebrow: "Partner With Us", ac_sponsor_title: "Sponsorship", ac_sponsor_highlight: "Opportunities",
    ac_sponsor_desc: "Position your brand at the centre of Africa's most celebrated annual festival.",
    ac_sponsor_cta: "Get in Touch",
    ac_cta_eyebrow: "Interested?", ac_cta_title: "Get Involved with", ac_cta_highlight: "Africa Celebrates",
    ac_cta_body: "Whether you're interested in sponsorship, media partnerships, or attending the event, reach out to the AfroNova team directly.",
    ac_cta_btn: "Contact AfroNova", ac_cta_btn2: "Official Event Website",
  },
  am: {
    nav_home: "መነሻ", nav_about: "ስለ እኛ", nav_services: "አገልግሎቶች",
    nav_portfolio: "ፖርትፎሊዮ", nav_news: "ዜና", nav_partners: "አጋሮች",
    nav_portal: "አሳዳሪ ፖርታል", nav_contact: "አግኙን",
    hero_badge: "ፓን-አፍሪካዊ · ዝግጅቶች · ሚዲያ · ፈጠራ · ማስተዋወቅ",
    hero_sub1: "ዝግጅቶችን ብቻ አናስተናግድም,",
    hero_sub2: "እንቅስቃሴዎችን እናቀጣጥላለን።",
    hero_body: "አፍሮኖቫ የአፍሪካን ባሕላዊ ቅርስ፣ ፈጠራ እና ፈጠራ ታላቅነት ለማክበር፣ ለማጉላት እና ለማስተዋወቅ ቁርኝተኛ የሆነ ቀዳሚ ፓን-አፍሪካዊ ድርጅት ነው። ዋና መሥሪያ ቤቱ አዲስ አበባ ሲሆን በ50+ አገሮች ይሠራል።",
    hero_cta_discover: "አፍሮኖቫን ያስሱ",
    hero_cta_services: "አገልግሎቶቻችን",
    hero_cta_work: "ከኛ ጋር ይሥሩ",
    countdown_badge: "6ኛ እትም · ዋና ዝግጅት",
    countdown_title1: "አፍሪካ", countdown_title2: "ሴሌብሬትስ", countdown_title3: "2026",
    countdown_theme: "\"አንድ አፍሪካ፣ አንድ ህዝብ: ባሕልን፣ ፈጠራን እና ድርጅትን ለጋራ ብልጽግና አንድ ማድረግ\"",
    countdown_date: "ህዳር 10 to 15, 2026",
    countdown_venue: "የአፍሪካ ህብረት ዋና መሥሪያ ቤት እና UNECA፣ አዲስ አበባ",
    countdown_label: "እስከ ዝግጅቱ ያለው ቆጠራ",
    countdown_visit: "ይፋዊ ድርጣቢያ ይጎብኙ",
    countdown_details: "ሙሉ የዝግጅት ዝርዝሮች",
    stat1_label: "የደረሱባቸው አገሮች", stat2_label: "ዋና አገልግሎት ምሰሶዎች",
    stat3_label: "ስትራቴጂካዊ አጋሮች", stat4_label: "በዓመት የሚደረሰውን ህይወት",
    who_eyebrow: "እኛ ማን ነን", who_title: "ለውጥ አምጪ ሃይል", who_highlight: "ለአፍሪካ",
    who_body1: "አፍሮኖቫ ማህበረሰቦችን በሚያበቃ፣ ባሕሎችን ድልድይ በሚያደርግ እና ታማኝ የአፍሪካ ትርክቶችን ወደ ዓለም አቀፍ መድረክ ፊት ለፊት በሚያቀርብ ሁሉ-ዙሪያ ልምዶችን ዘርግቶ ይሠራል።",
    who_body2: "ከከፍተኛ ተጽእኖ ዝግጅቶች እስከ አስደናቂ ሚዲያ ትርክቶች፣ አፍሮኖቫ ከአገልጋዮቹ የበለጠ ነው, አፍሪካ እንዴት እንደምትታይ፣ እንደምትሰማ እና እንደምትታወስ የሚቀይር እንቅስቃሴ ነው። ይፋዊ ዓቢይ አጋር",
    who_partner: "ሌጀንዳሪ ጎልድ ሊሚቴድ",
    who_story: "ታሪካችን",
    who_mission_label: "ተልዕኮ",
    who_mission: "የአፍሪካን ድምጾች ለማጉላት፣ ባሕላዊ ኩራትን ለማሳደግ እና ትርጉም ያለው ለውጥ ለማምጣት, ዓለም አቀፍ ዝግጅቶች፣ ፈጠራዊ ሚዲያ እና ባሕላዊ ስትራቴጂካዊ ግንኙነቶች።",
    who_vision_label: "ራዕይ",
    who_vision: "የአፍሪካ ዋናዋ የዝግጅት እና ሚዲያ ማዕከል ለመሆን, ባሕሎች የሚገናኙበት እና ታማኝ የአፍሪካ ታሪኮች ዓለም አቀፍ አተያዮችን የሚቀርጹበት ታማኝ መድረክ።",
    who_location: "አዲስ አበባ፣ ኢትዮጵያ",
    who_location_desc: "የአፍሪካ ዲፕሎማሲያዊ ዋና ከተማ፣ ከአፍሪካ ህብረት ቅርብ።",
    services_eyebrow: "የምናደርገው", services_title: "አምስት ምሰሶዎች", services_highlight: "የፓን-አፍሪካ ልዕቀት",
    services_desc: "ዝግጅቶች፣ ሚዲያ፣ ማስታወቂያ፣ ህትመት እና ብራንድ ምርቶች ላይ ሁሉ-ዙሪያ አቅሞች።",
    services_all: "ሁሉም አገልግሎቶች", services_learn: "ተጨማሪ ይወቁ",
    why_eyebrow: "ለምን አፍሮኖቫ", why_title: "የሚለዩን ምን ነው", why_highlight: "",
    work_eyebrow: "ታዋቂ ሥራዎች", work_title: "የሚገልጹን", work_highlight: "ፕሮጀክቶች",
    work_desc: "አፍሮኖቫ ባህሪ ላቲኑ ያስረከባቸው ሥራዎች ቅኝት።",
    work_portfolio: "ሙሉ ፖርትፎሊዮ", work_view: "ፕሮጀክቱን ይዩ", work_flagship: "ዋና",
    partners_label: "የምንታመናቸው አጋሮች እና ተባባሪዎች",
    cta_eyebrow: "ከኛ ጋር ይሥሩ", cta_title: "አስደናቂ ነገር", cta_highlight: "እንፍጠር",
    cta_body: "ዓለም አቀፍ ዝግጅት፣ አስደናቂ ዶኩሜንተሪ፣ ፓን-አፍሪካ ዘመቻ ወይም የህትመት ፕሮጀክት ቢያስፈልግዎ, አፍሮኖቫ ያቀርባል።",
    cta_start: "ውይይት ይጀምሩ", cta_explore: "አገልግሎቶችን ያስሱ",
    footer_tagline: "አዲሲቷ አፍሪካን ብራንድ ማድረግ። ያልተወሰኑ እድሎች። ዝግጅቶችን ብቻ አናስተናግድም, እንቅስቃሴዎችን እናቀጣጥላለን።",
    footer_rights: "© 2026 አፍሮኖቫ። ፓን-አፍሪካዊ · ዝግጅቶች · ሚዲያ · ፈጠራ · ማስተዋወቅ። መብቱ በሕግ የተጠበቀ ነው።",
    footer_stay: "ዘመናዊ ሁኑ", footer_stay_desc: "የቅርብ ዜናዎችን፣ የዝግጅት ዝመናዎችን እና ብቸኛ ማስታወቂያዎችን ያግኙ።",
    footer_subscribe: "ይመዝገቡ", footer_subscribed: "በዝርዝሩ ላይ ናዎት። ወደ አፍሮኖቫ እንኳን ደህና መጡ!",
    footer_company: "ድርጅት", footer_event: "ዝግጅት",
    cat_institutional: "ተቋማዊ", cat_strategic: "ስትራቴጂካዊ", cat_diplomatic: "ዲፕሎማሲያዊ",
    cat_corporate: "ኮርፖሬት", cat_media: "ሚዲያ", cat_cultural: "ባሕላዊ",
    cat_hospitality: "ማስተናገጃ", cat_government: "መንግስት",
    news_cat_all: "ሁሉም", news_cat_event: "ዝግጅት", news_cat_partner: "አጋርነት",
    news_cat_exhibitors: "አሳዳሪዎች", news_cat_business: "ንግድ",
    news_cat_recap: "ማጠቃለያ", news_cat_production: "ምርት",
    ac_h1_title: "ጋላ ፋሽን እና ሽልማቶች", ac_h1_desc: "ባሕላዊ ትርኢቶች፣ ባህላዊ ዳንስ እና ሽልማት ሥነ-ስርዓት።",
    ac_h2_title: "ንግድ ፎረሞች",          ac_h2_desc: "ፓን-አፍሪካዊ ንግድ፣ ቴክኖሎጂ እና ኢንቨስትመንት ላይ ውይይቶች።",
    ac_h3_title: "40+ አገሮች ኤግዚቢሽን",  ac_h3_desc: "ከፓን-አፍሪካዊ ዲያስፖራ ወኪሎች ጋር አርቲዛኖች እና ኩባንያዎች።",
    ac_h4_title: "ዲያስፖራ ተሳትፎ",       ac_h4_desc: "የዲያስፖራ ማህበረሰብን ከአፍሪካዊ ዕድሎች ጋር ያገናኛል።",
    ac_h5_title: "ባሕላዊ ትርኢት",        ac_h5_desc: "ፋሽን፣ ምስላዊ ጥበብ፣ ፊልም፣ ሙዚቃ እና ትርኢቶች።",
    ac_h6_title: "ፓን-አፍሪካዊ ሽልማቶች",  ac_h6_desc: "ታላላቅ ሰዎችን እና ድርጅቶችን ያወቅቃል።",
    prog1_title: "መክፈቻ ሥነ-ስርዓት", prog2_title: "የንግድ ቀን 1", prog3_title: "የንግድ ቀን 2",
    prog4_title: "የባሕልና ጥበብ ቀን", prog5_title: "ጋላ ሽልማት ሌሊት", prog6_title: "የዝግጅት ማጠቃለያ",
    tier1_name: "ዋና ስፖንሰር", tier2_name: "ወርቅ ስፖንሰር", tier3_name: "ብር ስፖንሰር",
    partners_all: "ሁሉም",
    ed5: "5ኛ እትም", ed4: "4ኛ እትም", ed3: "3ኛ እትም", ed2: "2ኛ እትም", ed1: "1ኛ እትም",
    svc1_full_desc: "ከፌስቲቫሎች እስከ ጉባዔዎች አፍሮኖቫ ሙሉ ዝግጅቶችን ያቀርባል።",
    svc1_f1: "የባሕል ፌስቲቫሎች፣ ፎረሞች እና የኤዩ ዝግጅቶች",
    svc1_f2: "ዝርዝር ዲዛይን፣ ሎጂስቲክስ እና ደህንነት",
    svc1_f3: "ታዋቂ እንግዶች አስተዳደር",
    svc1_f4: "ዲጂታል/ቪርቹዋል ልምምዶች",
    svc1_f5: "ሰነዶች እና ድህረ-ዝግጅት ይዘት",
    svc1_cta: "ዝግጅትዎን ያቅዱ",
    svc2_title: "ሚዲያ ምርት", svc2_desc: "4K ፊልሞች፣ ፖድካስቶች፣ ብሮድካስት እና ብራንድ ይዘቶች።",
    svc2_full_desc: "ሲኒማቲካዊ ትርክት ከባሕላዊ ሥሮቸ ጋር።",
    svc2_f1: "ዶኩሜንተሪ እና ፖድካስት",
    svc2_f2: "4K ቪዲዮ እና TV ስርጭት",
    svc2_f3: "የዝግጅት ሽፋን እና ሙዚቃ ቪዲዮ",
    svc2_f4: "ባሕላዊ ይዘቶች",
    svc2_f5: "ቀጥታ ብሮድካስት",
    svc2_cta: "ፕሮጀክት ይጀምሩ",
    svc3_title: "ስትራቴጂካዊ ማስታወቂያ", svc3_desc: "በ10+ ቋንቋዎች ዘመቻዎች እና ማህበራዊ ሚዲያ ማስተዳደር።",
    svc3_full_desc: "ፓን-አፍሪካዊ ብራንድ ዘመቻዎች።",
    svc3_f1: "ዒላማ ዲጂታል ዘመቻዎች በ10+ ቋንቋዎች",
    svc3_f2: "ብዙ ቋንቋ ይዘት ፈጠራ",
    svc3_f3: "ማህበራዊ ሚዲያ አስተዳደር",
    svc3_f4: "ማስታወቂያ ቁሳቁሶች",
    svc3_f5: "ስፖንሰርሺፕ ማስፈጸሚያ",
    svc3_cta: "ዘመቻ ይጀምሩ",
    svc4_title: "ህትመት እና ብራንድ ምርቶች", svc4_desc: "ብሮሸሮች፣ ምልክቶች፣ ልብስ እና ስጦታዎች።",
    svc4_full_desc: "ፕሪሚየም ፊዚካዊ ብራንድ ነጥቦች።",
    svc4_f1: "ብሮሸሮች፣ ፕሮግራሞች እና ምልክቶች",
    svc4_f2: "ብራንድ ምርቶች",
    svc4_f3: "ፓን-አፍሪካዊ ዲዛይን",
    svc4_f4: "ኮርፖሬት ስጦታዎች",
    svc4_cta: "ዋጋ ያግኙ",
    svc5_title: "ህትመት እና ዲጂታል ሚዲያ", svc5_desc: "ዲጂታል መጽሔቶች፣ ቡክ ፕሮጀክቶች እና ብራንድ ትርክቶች።",
    svc5_full_desc: "ብራንድ ይዘቶች ከዲጂታል መጽሔቶች እስከ ቡክ ፕሮጀክቶች።",
    svc5_f1: "ዲጂታል መጽሔቶች",
    svc5_f2: "ቡክ ፕሮጀክቶች",
    svc5_f3: "ብራንድ ትርክቶች",
    svc5_f4: "ዲጂታል ህትመት",
    svc5_cta: "ህትመት ይጀምሩ",
    why1_title: "ፓን-አፍሪካዊ ደርስ", why1_desc: "5,000+ አስተሳሰቢ መሪዎች; 50+ አገሮች።",
    why2_title: "ባሕላዊ ታማኝነት", why2_desc: "አፍሪካዊ ትኩረት, አናጽናናም፣ እናጉላለን።",
    why3_title: "ፈጠራ", why3_desc: "ዘመናዊ ቴክኖሎጂ እና ዲጂታል ትርክት።",
    why4_title: "ሊለካ ተጽዕኖ", why4_desc: "500K+ ሚዲያ ስሜቶች; 70%+ ስፖንሰር ማቆያ።",
    fw1_title: "አፍሪካ ሴሌብሬትስ 2025", fw1_type: "ዋና ዝግጅት", fw1_desc: "ኢትዮጵያ ውስጥ ዋና አፈጻፀም አጋር, 20+ ፎረሞች፣ 5,000+ ተሳታፊዎች።",
    fw2_title: "AFRIMA 2025", fw2_type: "የሙዚቃ ጉባዔ", fw2_desc: "ሙሉ ዝግጅት አስተዳደር እና ስትራቴጂካዊ ብራንድ አቀማመጥ።",
    fw3_title: "የኢትዮጵያ ቱሪዝም ዘመቻ", fw3_type: "ማስታወቂያ", fw3_desc: "15M+ ተመልካቾች ደርሷል።",
    tag_events: "ዝግጅቶች", tag_media: "ሚዲያ", tag_advertising: "ማስታወቂያ", tag_publishing: "ህትመት", tag_merch: "ምርቶች",
    about_eyebrow: "ስለ አፍሮኖቫ", about_h1: "አዲሲቷ አፍሪካን ብራንድ ማድረግ።", about_h1b: "ያልተወሰኑ እድሎች።",
    about_hero_body: "አፍሮኖቫ የአፍሪካን ባሕላዊ ቅርስ ለማክበር ቁርኝተኛ ቀዳሚ ፓን-አፍሪካዊ ድርጅት ነው። ከአገልጋዮቹ የበለጠ ነን, አፍሪካ እንዴት እንደምትታይ፣ እንደምትሰማ እና እንደምትታወስ የሚቀይር እንቅስቃሴ።",
    about_who_eyebrow: "እኛ ማን ነን", about_who_title: "ለውጥ አምጪ", about_who_highlight: "ሃይል ለአፍሪካ",
    about_p1: "አፍሮኖቫ ማህበረሰቦችን የሚያበቃ ሁሉ-ዙሪያ ልምዶችን ዘርግቶ ይሠራል።",
    about_p2: "በ50+ አገሮች ስንሠራ ዋና መሥሪያ ቤታችን አዲስ አበባ ላይ ነው።",
    about_p3: "የ", about_p3b: " ይፋዊ ዓቢይ አጋር ነን።",
    about_our_services: "አገልግሎቶቻችን",
    about_countries: "አገሮች", about_reached: "ደርሰናል",
    about_mission_h: "ተልዕኳችን", about_mission_body: "የአፍሪካን ድምጾች ለማጉላት እና ትርጉም ያለው ለውጥ ለማምጣት።",
    about_vision_h: "ራዕያችን", about_vision_body: "የአፍሪካ ዋናዋ የዝግጅት እና ሚዲያ ማዕከል ለመሆን።",
    about_partnership_badge: "ስትራቴጂካዊ አጋርነት", about_partnership_h: "ይፋዊ ዓቢይ አጋር",
    about_partnership_body: "ከሌጀንዳሪ ጎልድ ሊሚቴድ ጋር ያለን አጋርነት ዓለም አቀፍ ኢንቨስትመንት እና ልምድ ያስገኛል።",
    about_values_eyebrow: "የሚያንቀሳቅሰን", about_values_title: "ዋና ድርጅታዊ", about_values_highlight: "እሴቶች",
    about_lead_eyebrow: "አመራር", about_lead_title: "ከበስተጀርባ ያለው ሰው", about_lead_highlight: "አፍሮኖቫ",
    about_net_eyebrow: "አውታረ ማህበራችን", about_net_title: "የምንታመናቸው", about_net_highlight: "አጋሮች",
    about_view_partners: "ሁሉም አጋሮችን ይዩ",
    val1_title: "ሙያዊነት", val1_desc: "በእያንዳንዱ ፕሮጀክት ዓለም አቀፍ ደረጃዎች።",
    val2_title: "ክብር እና ታማኝነት", val2_desc: "ሐቀኛ፣ ሥነ-ምግባራዊ እና ባሕልን ያከብራል።",
    val3_title: "ፈጠራ", val3_desc: "ደፋር፣ ፈጠራዊ አስተሳሰብ።",
    val4_title: "ትብብር", val4_desc: "ድንበሮችን እና ማህበረሰቦችን ያዋህዳል።",
    val5_title: "አካታችነት", val5_desc: "ለሁሉም ባሕሎች እና አመለካከቶች ቦታ ይፈጥራል።",
    val6_title: "ተጽዕኖ ተኮር", val6_desc: "ስኬትን በእውነተኛ ለውጥ ይለካዋል።",
    val7_title: "ባሕላዊ ኩራት", val7_desc: "የአፍሪካ ማንነት የሁሉ ነገር ማዕከል ነው።",
    val8_title: "ቀጣይ ትምህርት", val8_desc: "ሁልጊዜ እያደገ እና እያዳበረ።",
    svc_eyebrow: "የምናደርገው", svc_h1: "አምስት ምሰሶዎች", svc_h1b: "የፓን-አፍሪካ ልዕቀት",
    svc_hero_body: "ዝግጅቶች፣ ሚዲያ፣ ማስታወቂያ፣ ህትመት እና ዲጂታል ህትመት, አፍሮኖቫ ሁሉ-ዙሪያ ፓን-አፍሪካዊ ልዕቀት ያቀርባል።",
    svc_process_eyebrow: "እንዴት እንሠራለን", svc_process_title: "ሂደታችን",
    svc_cta_h: "አስደናቂ ነገር", svc_cta_hb: "አብረን እንፍጠር።",
    svc_cta_body: "ስለ ፕሮጀክትዎ ይንገሩን, ውስጥ 48 ሰዓት ሀሳብ እናቀርባለን።",
    svc_cta_btn: "ሀሳብ ያግኙ",
    proc1_title: "ፍለጋ", proc1_desc: "እናዳምጣለን፣ እናጠናለን እና ዓላማዎን እናረዳለን።",
    proc2_title: "ስትራቴጂ", proc2_desc: "የጊዜ ሰሌዳ፣ በጀት እና ሊለካ የሚችል ዕቅድ።",
    proc3_title: "ምርት", proc3_desc: "ቡድናቸን ልዕቀትና ፈጠራ ይፈጽማሉ።",
    proc4_title: "ማቅረብ", proc4_desc: "ወቅቱን ጠብቆ፣ ሙሉ ሪፖርት።",
    contact_eyebrow: "እንነጋገር", contact_h1: "ያግኙን", contact_h1b: "",
    contact_hero_body: "ዝግጅት ቢያቅዱ፣ ይዘት ቢያቀርቡ፣ ዘመቻ ቢጀምሩ ወይም ስለ አፍሮኖቫ ማወቅ ቢፈልጉ, ደስ ይለናል።",
    contact_office: "ዋና መሥሪያ ቤት", contact_phone: "ስልክ", contact_hours: "የቢሮ ሰዓቶች",
    contact_hours_val: "ሰኞ  to  ዓርብ · ጠ/9፡00  to  ከሰ/5፡00 (ምስራቅ አፍሪካ ሰዓት)",
    contact_follow: "ተከተሉን",
    contact_direct: "ቀጥታ ግንኙነት",
    contact_form_eyebrow: "መልዕክት ይላኩ", contact_form_title: "እዚህ ነን", contact_form_highlight: "ለእናንተ",
    contact_send: "መልዕክት ላኩ",
    contact_map: "ያግኙን, አፍሪካ አቬኑ፣ አዲስ አበባ",
    contact_success: "መልዕክትዎ ደርሷል። ውስጥ 1 to 2 ሥራ ቀናት ምላሽ እንሰጣለን።",
    contact_field_name: "ሙሉ ስም", contact_field_name_ph: "ሙሉ ስምዎ",
    contact_field_email: "ኢሜይል አድራሻ",
    contact_field_phone: "ስልክ ቁጥር", contact_field_phone_ph: "+1 234 567 8900",
    contact_field_inquiry: "የጥያቄ ዓይነት",
    contact_field_msg: "መልዕክት", contact_field_msg_ph: "ስለ ፕሮጀክትዎ ወይም ጥያቄዎ ይንገሩን...",
    contact_inquiry_general: "አጠቃላይ ጥያቄ", contact_inquiry_event: "የዝግጅት አስተዳደር",
    contact_inquiry_media: "ሚዲያ ምርት", contact_inquiry_ads: "ማስታወቂያ",
    contact_inquiry_ac: "አፍሪካ ሴሌብሬትስ 2026", contact_inquiry_sponsor: "ስፖንሰርሺፕ",
    contact_inquiry_press: "ሚዲያ / ፕሬስ", contact_inquiry_other: "ሌላ",
    partners_eyebrow: "አውታረ ማህበራችን", partners_h1: "የምንታመናቸው", partners_h1b: "አጋሮች",
    partners_hero_body: "አፍሮኖቫ ከ50+ አገሮች ጋር ይሠራል። ተጨማሪ ለማወቅ ካርዱን ያንዣብቡ።",
    partners_stat1: "ንቁ አጋሮች", partners_stat2: "የሚሸፈኑ አገሮች",
    partners_stat3: "የአጋር ምድቦች", partners_stat4: "የትብብር ዓመቶች",
    partners_hover: "ተጨማሪ ለማወቅ ያንዣብቡ",
    partners_cta_badge: "የአጋርነት እድሎች",
    partners_cta_h: "አጋር", partners_cta_hb: "ይሁኑ",
    partners_cta_body: "የአፍሪካን ባሕል፣ ንግድ እና ፈጠራ የሚቀርጸውን አፍሮኖቫ አውታረ ማህበር ይቀላቀሉ።",
    partners_cta_btn: "ያግኙን", partners_about_btn: "ስለ አፍሮኖቫ ይወቁ",
    portfolio_eyebrow: "ሥራዎቻችን", portfolio_h1: "ፖርትፎሊዮ እና", portfolio_h1b: "ታዋቂ ፕሮጀክቶች",
    portfolio_hero_body: "ከአፍሪካ ሴሌብሬትስ እስከ AFRIMA, እንቅስቃሴዎችን እናቀጣጥላለን።",
    portfolio_featured_eyebrow: "ታዋቂ ሥራዎች", portfolio_featured_title: "ዋና", portfolio_featured_highlight: "ፕሮጀክቶች",
    portfolio_editions_eyebrow: "አፍሪካ ሴሌብሬትስ", portfolio_editions_title: "ያለፉ", portfolio_editions_highlight: "እትሞች",
    portfolio_gallery_eyebrow: "ጋለሪ", portfolio_gallery_title: "የልዕቀት", portfolio_gallery_highlight: "ቅጽበቶች",
    portfolio_media_eyebrow: "ጥናቶች", portfolio_media_title: "ሚዲያ እና ምርት", portfolio_media_highlight: "ፕሮጀክቶች",
    portfolio_attendees: "ተሳታፊዎች", portfolio_nations: "አገሮች",
    news_eyebrow: "የቅርብ ዝመናዎች", news_h1: "ዜና እና", news_h1b: "ፕሬስ",
    news_hero_body: "ፕሬስ መልቀቂያዎች፣ የዝግጅት ዝመናዎች እና ታሪኮች ከአፍሮኖቫ ዓለም።",
    news_featured: "ታዋቂ", news_read: "አንብቡ",
    ac_badge: "6ኛ እትም · ፓን-አፍሪካዊ ፌስቲቫል",
    ac_theme: "\"አንድ አፍሪካ፣ አንድ ህዝብ: ባሕልን፣ ፈጠራን እና ድርጅትን ለጋራ ብልጽግና አንድ ማድረግ\"",
    ac_date: "ህዳር 10 to 15, 2026", ac_venue: "የአፍሪካ ህብረት ዋ/መ/ቤ እና UNECA", ac_nations: "40+ አፍሪካዊ አገሮች",
    ac_countdown_label: "እስከ አፍሪካ ሴሌብሬትስ 2026 ቆጠራ",
    ac_visit: "ይፋዊ ድርጣቢያ ይጎብኙ", ac_download: "ፕሮግራም አውርዱ",
    ac_highlights_eyebrow: "ምን ይጠበቃል", ac_highlights_title: "ፕሮግራም", ac_highlights_highlight: "ሃይላይቶች",
    ac_schedule_eyebrow: "6 የልዕቀት ቀናት", ac_schedule_title: "የዝግጅት", ac_schedule_highlight: "መርሃ ግብር",
    ac_schedule_pdf: "ሙሉ PDF አውርዱ",
    ac_venues_eyebrow: "ቦታዎች", ac_venues_title: "የ", ac_venues_highlight: "አዲስ አበባ ልብ",
    ac_venue1_badge: "ዋና ቦታ", ac_venue2_badge: "የሸሪካ ቦታ",
    ac_venue1_name: "የአፍሪካ ህብረት ዋና መሥሪያ ቤት",
    ac_venue1_desc: "የፓን-አፍሪካዊ ዲፕሎማሲ ምልክት, የዋና ቦታ ዝግጅቶች ቤት።",
    ac_venue2_name: "UNECA, ለአፍሪካ የተባበሩት መንግስታት የኢኮኖሚ ኮሚሽን",
    ac_venue2_desc: "የኢንቨስትመንት እና ፈጠራ መድረኮች ምቹ ቦታ።",
    ac_sponsor_eyebrow: "ከኛ ጋር ተባበሩ", ac_sponsor_title: "ስፖንሰርሺፕ", ac_sponsor_highlight: "እድሎች",
    ac_sponsor_desc: "ብራንድዎን የአፍሪካ ታላቅ ፌስቲቫል ማዕከል ላይ ያስቀምጡ።",
    ac_sponsor_cta: "ያግኙን",
    ac_cta_eyebrow: "ፍላጎት አለ?", ac_cta_title: "ተሳተፉ", ac_cta_highlight: "አፍሪካ ሴሌብሬትስ",
    ac_cta_body: "ለስፖንሰርሺፕ፣ ሚዲያ አጋርነት ወይም ዝግጅቱ, ቀጥታ ያግኙን።",
    ac_cta_btn: "አፍሮኖቫን ያግኙ", ac_cta_btn2: "ይፋዊ ድርጣቢያ",
  },
  fr: {
    nav_home: "Accueil", nav_about: "À propos", nav_services: "Services",
    nav_portfolio: "Portfolio", nav_news: "Actualités", nav_partners: "Partenaires",
    nav_portal: "Portail Exposants", nav_contact: "Contact",
    hero_badge: "Panafricain · Événements · Médias · Innovation · Promotion",
    hero_sub1: "Nous ne faisons pas qu'organiser des événements,",
    hero_sub2: "nous allument des mouvements.",
    hero_body: "AfroNova est une entreprise panafricaine de premier plan dédiée à célébrer, amplifier et promouvoir le patrimoine culturel, l'innovation et l'excellence créative de l'Afrique. Siège à Addis-Abeba, opérant dans 50+ pays.",
    hero_cta_discover: "Découvrir AfroNova",
    hero_cta_services: "Nos services",
    hero_cta_work: "Travailler avec nous",
    countdown_badge: "6e Édition · Événement phare",
    countdown_title1: "Africa", countdown_title2: "Celebrates", countdown_title3: "2026",
    countdown_theme: "\"Une Afrique, Un Peuple : Unir la Culture, l'Innovation et l'Entreprise pour un Avenir Prospère Commun\"",
    countdown_date: "10 to 15 novembre 2026",
    countdown_venue: "Siège de l'UA et UNECA, Addis-Abeba",
    countdown_label: "Compte à rebours jusqu'à l'événement",
    countdown_visit: "Visiter le site officiel",
    countdown_details: "Détails complets de l'événement",
    stat1_label: "Pays atteints", stat2_label: "Piliers de services",
    stat3_label: "Partenaires stratégiques", stat4_label: "Vies impactées annuellement",
    who_eyebrow: "Qui sommes-nous", who_title: "Une force transformatrice", who_highlight: "pour l'Afrique",
    who_body1: "AfroNova agit comme une force transformatrice, organisant des expériences de bout en bout qui autonomisent les communautés, relient les cultures et positionnent les récits africains authentiques à l'avant-scène mondiale.",
    who_body2: "Des événements à fort impact aux récits multimédias captivants, AfroNova est plus qu'un prestataire, c'est un mouvement qui redéfinit la façon dont l'Afrique est vue, entendue et mémorisée. Partenaire local officiel de",
    who_partner: "Legendary Gold Limited",
    who_story: "Notre histoire",
    who_mission_label: "Mission",
    who_mission: "Amplifier les voix africaines, favoriser la fierté culturelle et impulser un changement significatif à travers des événements de classe mondiale, des multimédias innovants et des communications stratégiques culturellement ancrées.",
    who_vision_label: "Vision",
    who_vision: "Devenir le principal hub d'événements et de médias d'Afrique, une plateforme de confiance où les cultures convergent et où les histoires africaines authentiques façonnent les perspectives mondiales.",
    who_location: "Addis-Abeba, Éthiopie",
    who_location_desc: "La capitale diplomatique de l'Afrique, à deux pas de l'Union africaine.",
    services_eyebrow: "Ce que nous faisons", services_title: "Cinq piliers de", services_highlight: "l'excellence panafricaine",
    services_desc: "Capacités de bout en bout en événements, médias, publicité, édition et marchandisage de marque.",
    services_all: "Tous les services", services_learn: "En savoir plus",
    why_eyebrow: "Pourquoi AfroNova", why_title: "Ce qui nous distingue", why_highlight: "",
    work_eyebrow: "Travaux en vedette", work_title: "Projets qui nous", work_highlight: "définissent",
    work_desc: "Un aperçu du travail livré par AfroNova sur le continent.",
    work_portfolio: "Portfolio complet", work_view: "Voir le projet", work_flagship: "Phare",
    partners_label: "Partenaires et collaborateurs de confiance",
    cta_eyebrow: "Travaillez avec nous", cta_title: "Construisons quelque chose", cta_highlight: "d'extraordinaire",
    cta_body: "Que vous ayez besoin d'un événement de classe mondiale, d'un documentaire captivant, d'une campagne panafricaine ou d'un projet d'édition, AfroNova livre.",
    cta_start: "Commencer une conversation", cta_explore: "Explorer les services",
    footer_tagline: "Branding la Nouvelle Afrique. Des possibilités sans limites. Nous n'organisons pas seulement des événements, nous allument des mouvements.",
    footer_rights: "© 2026 AfroNova. Panafricain · Événements · Médias · Innovation · Promotion. Tous droits réservés.",
    footer_stay: "Restez informé", footer_stay_desc: "Recevez les dernières nouvelles, mises à jour et annonces exclusives.",
    footer_subscribe: "S'abonner", footer_subscribed: "Vous êtes sur la liste. Bienvenue chez AfroNova !",
    footer_company: "Entreprise", footer_event: "Événement",
    cat_institutional: "Institutionnel", cat_strategic: "Stratégique", cat_diplomatic: "Diplomatique",
    cat_corporate: "Corporate", cat_media: "Médias", cat_cultural: "Culturel",
    cat_hospitality: "Hôtellerie", cat_government: "Gouvernement",
    news_cat_all: "Tout", news_cat_event: "Événement", news_cat_partner: "Partenariat",
    news_cat_exhibitors: "Exposants", news_cat_business: "Affaires",
    news_cat_recap: "Compte rendu", news_cat_production: "Production",
    ac_h1_title: "Gala Mode & Récompenses",   ac_h1_desc: "Spectacles culturels, danse traditionnelle et cérémonie de remise de prix.",
    ac_h2_title: "Forums Affaires & Commerce", ac_h2_desc: "Discussions de haut niveau sur les affaires, la technologie et l'investissement intra-africains.",
    ac_h3_title: "Exposition 40+ Nations",     ac_h3_desc: "Artisans, vendeurs et équipes d'entreprise de tout le continent africain.",
    ac_h4_title: "Participation Diaspora",     ac_h4_desc: "Connecter la diaspora africaine aux opportunités, à la culture et à la communauté continentales.",
    ac_h5_title: "Vitrine Culturelle",         ac_h5_desc: "Mode, arts visuels, film, musique et spectacles traditionnels représentant le continent.",
    ac_h6_title: "Prix Panafricains",          ac_h6_desc: "Reconnaître les individus, entreprises et institutions exceptionnels qui font avancer l'Afrique.",
    prog1_title: "Cérémonie d'ouverture", prog2_title: "Journée Affaires 1", prog3_title: "Journée Affaires 2",
    prog4_title: "Journée Culture & Arts", prog5_title: "Soirée Gala & Récompenses", prog6_title: "Cérémonie de clôture",
    tier1_name: "Sponsor Titre", tier2_name: "Sponsor Or", tier3_name: "Sponsor Argent",
    partners_all: "Tous",
    ed5: "5e Édition", ed4: "4e Édition", ed3: "3e Édition", ed2: "2e Édition", ed1: "1re Édition",
    svc1_full_desc: "Des festivals culturels aux sommets d'affaires, AfroNova livre des expériences d'événements complètes.",
    svc1_f1: "Festivals culturels, forums d'affaires et rassemblements UA",
    svc1_f2: "Conception d'événements, gestion logistique et sécurité",
    svc1_f3: "Gestion de personnalités et services de protocole",
    svc1_f4: "Expériences hybrides avec intégration VR/AR",
    svc1_f5: "Création de contenu héritage et documentation post-événement",
    svc1_cta: "Planifiez votre événement",
    svc2_title: "Production multimédia", svc2_desc: "Documentaires 4K, podcasts, couverture broadcast et contenu de marque.",
    svc2_full_desc: "Storytelling cinématographique et ancré culturellement qui positionne les récits africains à l'avant-scène mondiale.",
    svc2_f1: "Développement de documentaires et podcasts",
    svc2_f2: "Vidéo 4K & Dolby, distribution TV et courts métrages",
    svc2_f3: "Couverture d'événements, clips et séries de marque",
    svc2_f4: "Contenu culturel et commercial par des créatifs africains",
    svc2_f5: "Production broadcast multisupport en direct",
    svc2_cta: "Démarrer un projet",
    svc3_title: "Publicité stratégique", svc3_desc: "Campagnes ciblées en 10+ langues et gestion des réseaux sociaux.",
    svc3_full_desc: "Campagnes de marque panafricaines qui résonnent à travers les cultures, langues et frontières.",
    svc3_f1: "Campagnes numériques ciblées en 10+ langues",
    svc3_f2: "Création de contenu multilingue et localisé culturellement",
    svc3_f3: "Gestion des réseaux sociaux et analyses IA",
    svc3_f4: "Brochures AR, campagnes extérieures et collateral imprimé",
    svc3_f5: "Activation de parrainage et positionnement stratégique",
    svc3_cta: "Lancer une campagne",
    svc4_title: "Impression et merchandising", svc4_desc: "Brochures, signalétique, vêtements et souvenirs personnalisés.",
    svc4_full_desc: "Points de contact physiques premium avec l'esthétique AfroNova, ancrés culturellement et durables.",
    svc4_f1: "Brochures, programmes, signalétique et kits d'événements",
    svc4_f2: "Merchandising de marque : vêtements, accessoires et souvenirs",
    svc4_f3: "Esthétique de design panafricain et matériaux durables",
    svc4_f4: "Coffrets cadeaux d'entreprise et collateral VIP",
    svc4_cta: "Obtenir un devis",
    svc5_title: "Publication et médias numériques", svc5_desc: "Magazines numériques, livres et récits de marque.",
    svc5_full_desc: "Contenu de marque qui informe, inspire et perdure, des magazines numériques aux livres sur la culture africaine.",
    svc5_f1: "Éditions de magazines numériques co-marquées et anthologies",
    svc5_f2: "Projets d'édition et éditoriaux sponsorisés",
    svc5_f3: "Storytelling de marque pour partenaires d'entreprise et culturels",
    svc5_f4: "Stratégie de contenu réseaux sociaux et édition numérique",
    svc5_cta: "Commencer à publier",
    why1_title: "Portée panafricaine", why1_desc: "Réseau de 5 000+ leaders; présence dans 50+ pays.",
    why2_title: "Intégrité culturelle", why2_desc: "Vision africaine avec exécution locale, nous n'imposons pas, nous amplifions.",
    why3_title: "Innovation", why3_desc: "Intégration AR/VR, analyses IA et storytelling numérique de pointe.",
    why4_title: "Impact mesurable", why4_desc: "500K+ impressions médias; taux de fidélisation des sponsors 70%+.",
    fw1_title: "Africa Celebrates 2025", fw1_type: "Événement phare", fw1_desc: "Partenaire principal en Éthiopie, 20+ forums, 5 000+ participants.",
    fw2_title: "AFRIMA 2025", fw2_type: "Conférence musicale", fw2_desc: "Facilitation complète et positionnement de marque panafricain.",
    fw3_title: "Campagne Tourisme Éthiopie", fw3_type: "Publicité", fw3_desc: "Campagne atteignant 15M+ de spectateurs.",
    tag_events: "Événements", tag_media: "Médias", tag_advertising: "Publicité", tag_publishing: "Édition", tag_merch: "Marchandise",
    about_eyebrow: "À propos d'AfroNova", about_h1: "Branding la Nouvelle Afrique.", about_h1b: "Des possibilités sans limites.",
    about_hero_body: "AfroNova est une entreprise panafricaine de premier plan dédiée à célébrer, amplifier et promouvoir le patrimoine culturel de l'Afrique. Nous sommes plus qu'un prestataire, nous sommes un mouvement.",
    about_who_eyebrow: "Qui sommes-nous", about_who_title: "Une force transformatrice", about_who_highlight: "pour l'Afrique",
    about_p1: "AfroNova organise des expériences de bout en bout qui autonomisent les communautés et positionnent les récits africains authentiques à l'avant-scène mondiale.",
    about_p2: "Opérant dans 50+ pays avec siège à Addis-Abeba, nous servons gouvernements, entreprises et communautés.",
    about_p3: "En tant que partenaire local officiel de", about_p3b: ", nous apportons portée et investissement mondiaux.",
    about_our_services: "Nos services",
    about_countries: "Pays", about_reached: "atteints",
    about_mission_h: "Notre Mission", about_mission_body: "Amplifier les voix africaines et impulser un changement significatif.",
    about_vision_h: "Notre Vision", about_vision_body: "Devenir le principal hub d'événements et de médias d'Afrique.",
    about_partnership_badge: "Partenariat stratégique", about_partnership_h: "Partenaire local officiel de",
    about_partnership_body: "Notre partenariat avec Legendary Gold Limited apporte investissements internationaux et expertise de classe mondiale à chaque projet AfroNova.",
    about_values_eyebrow: "Ce qui nous anime", about_values_title: "Valeurs organisationnelles", about_values_highlight: "fondamentales",
    about_lead_eyebrow: "Direction", about_lead_title: "La personne derrière", about_lead_highlight: "AfroNova",
    about_net_eyebrow: "Notre réseau", about_net_title: "Partenaires de", about_net_highlight: "confiance",
    about_view_partners: "Voir tous les partenaires",
    val1_title: "Professionnalisme", val1_desc: "Standards de classe mondiale dans chaque projet.",
    val2_title: "Respect et intégrité", val2_desc: "Honnête, éthique et culturellement sensible.",
    val3_title: "Créativité", val3_desc: "Pensée audacieuse et innovante.",
    val4_title: "Collaboration", val4_desc: "Construire des ponts entre les frontières.",
    val5_title: "Inclusivité", val5_desc: "Chaque voix africaine compte.",
    val6_title: "Focus sur l'impact", val6_desc: "Le succès mesuré par le changement réel.",
    val7_title: "Fierté culturelle", val7_desc: "Le patrimoine africain est notre pièce maîtresse.",
    val8_title: "Apprentissage continu", val8_desc: "Toujours en évolution pour mieux servir l'Afrique.",
    svc_eyebrow: "Ce que nous faisons", svc_h1: "Cinq piliers de", svc_h1b: "l'excellence panafricaine",
    svc_hero_body: "De la gestion d'événements à la production multimédia, publicité, marchandisage et édition, AfroNova livre.",
    svc_process_eyebrow: "Comment nous travaillons", svc_process_title: "Notre processus",
    svc_cta_h: "Construisons quelque chose", svc_cta_hb: "d'extraordinaire ensemble.",
    svc_cta_body: "Parlez-nous de votre projet, nous préparerons une proposition en 48 heures.",
    svc_cta_btn: "Obtenir une proposition",
    proc1_title: "Découverte", proc1_desc: "Nous écoutons et comprenons vos objectifs en profondeur.",
    proc2_title: "Stratégie", proc2_desc: "Plan sur mesure avec délais, budgets et KPIs mesurables.",
    proc3_title: "Production", proc3_desc: "Nos équipes exécutent avec précision et excellence créative.",
    proc4_title: "Livraison", proc4_desc: "Dans les délais, dans le budget, avec rapport complet.",
    contact_eyebrow: "Parlons", contact_h1: "Entrer en", contact_h1b: "contact",
    contact_hero_body: "Que vous planifiez un événement, produisiez du contenu, lanciez une campagne ou souhaitiez en savoir plus sur AfroNova, nous serions ravis de vous entendre.",
    contact_office: "Siège social", contact_phone: "Téléphone", contact_hours: "Heures de bureau",
    contact_hours_val: "Lundi  to  Vendredi · 9h00  to  17h00 (HEA)",
    contact_follow: "Suivez-nous",
    contact_direct: "Contact direct",
    contact_form_eyebrow: "Envoyer un message", contact_form_title: "Nous sommes là", contact_form_highlight: "pour vous",
    contact_send: "Envoyer le message",
    contact_map: "Nous trouver, Africa Avenue, Addis-Abeba",
    contact_success: "Votre message a été reçu. Nous vous répondrons dans 1 to 2 jours ouvrables.",
    contact_field_name: "Nom complet", contact_field_name_ph: "Votre nom complet",
    contact_field_email: "Adresse e-mail",
    contact_field_phone: "Numéro de téléphone", contact_field_phone_ph: "+1 234 567 8900",
    contact_field_inquiry: "Type de demande",
    contact_field_msg: "Message", contact_field_msg_ph: "Parlez-nous de votre projet...",
    contact_inquiry_general: "Demande générale", contact_inquiry_event: "Gestion d'événements",
    contact_inquiry_media: "Production multimédia", contact_inquiry_ads: "Publicité / Campagnes",
    contact_inquiry_ac: "Africa Celebrates 2026", contact_inquiry_sponsor: "Parrainage",
    contact_inquiry_press: "Médias / Presse", contact_inquiry_other: "Autre",
    partners_eyebrow: "Notre réseau", partners_h1: "Partenaires de", partners_h1b: "confiance",
    partners_hero_body: "AfroNova travaille avec des gouvernements, missions diplomatiques et organisations culturelles dans 50+ pays. Survolez une carte pour en savoir plus.",
    partners_stat1: "Partenaires actifs", partners_stat2: "Pays couverts",
    partners_stat3: "Catégories de partenaires", partners_stat4: "Années de collaboration",
    partners_hover: "Survolez pour en savoir plus",
    partners_cta_badge: "Opportunités de partenariat",
    partners_cta_h: "Devenir un", partners_cta_hb: "partenaire",
    partners_cta_body: "Rejoignez le réseau croissant d'AfroNova d'institutions et d'organisations façonnant l'avenir de la culture panafricaine.",
    partners_cta_btn: "Nous contacter", partners_about_btn: "En savoir plus sur AfroNova",
    portfolio_eyebrow: "Notre travail", portfolio_h1: "Portfolio &", portfolio_h1b: "Projets en vedette",
    portfolio_hero_body: "D'Africa Celebrates à l'AFRIMA jusqu'aux productions multimédias, la preuve que nous allument des mouvements.",
    portfolio_featured_eyebrow: "Travaux en vedette", portfolio_featured_title: "Projets", portfolio_featured_highlight: "phares",
    portfolio_editions_eyebrow: "Africa Celebrates", portfolio_editions_title: "Éditions", portfolio_editions_highlight: "passées",
    portfolio_gallery_eyebrow: "Galerie", portfolio_gallery_title: "Moments d'", portfolio_gallery_highlight: "excellence",
    portfolio_media_eyebrow: "Études de cas", portfolio_media_title: "Projets médias &", portfolio_media_highlight: "production",
    portfolio_attendees: "Participants", portfolio_nations: "Nations",
    news_eyebrow: "Dernières mises à jour", news_h1: "Actualités &", news_h1b: "Presse",
    news_hero_body: "Communiqués de presse, mises à jour d'événements, partenariats et histoires du monde d'AfroNova.",
    news_featured: "À la une", news_read: "Lire",
    ac_badge: "6e Édition · Festival panafricain",
    ac_theme: "\"Une Afrique, Un Peuple : Unir la Culture, l'Innovation et l'Entreprise pour un Avenir Prospère Commun\"",
    ac_date: "10 to 15 novembre 2026", ac_venue: "Siège UA & UNECA, Addis-Abeba", ac_nations: "40+ nations africaines",
    ac_countdown_label: "Compte à rebours jusqu'à Africa Celebrates 2026",
    ac_visit: "Visiter le site officiel", ac_download: "Télécharger le programme",
    ac_highlights_eyebrow: "À quoi s'attendre", ac_highlights_title: "Programme en", ac_highlights_highlight: "vedette",
    ac_schedule_eyebrow: "6 jours d'excellence", ac_schedule_title: "Programme de", ac_schedule_highlight: "l'événement",
    ac_schedule_pdf: "Télécharger le PDF complet",
    ac_venues_eyebrow: "Lieux", ac_venues_title: "Le cœur d'", ac_venues_highlight: "Addis-Abeba",
    ac_venue1_badge: "Lieu principal", ac_venue2_badge: "Lieu partenaire",
    ac_venue1_name: "Siège de l'Union africaine",
    ac_venue1_desc: "Le foyer emblématique de la diplomatie panafricaine, un symbole d'unité continentale.",
    ac_venue2_name: "UNECA, Commission économique des Nations Unies pour l'Afrique",
    ac_venue2_desc: "La principale institution économique de l'Afrique, cadre idéal pour les forums d'innovation.",
    ac_sponsor_eyebrow: "Partenez avec nous", ac_sponsor_title: "Opportunités de", ac_sponsor_highlight: "parrainage",
    ac_sponsor_desc: "Positionnez votre marque au centre du festival panafricain le plus célébré.",
    ac_sponsor_cta: "Nous contacter",
    ac_cta_eyebrow: "Intéressé ?", ac_cta_title: "Participez à", ac_cta_highlight: "Africa Celebrates",
    ac_cta_body: "Que vous soyez intéressé par le parrainage, les partenariats médias ou la participation, contactez directement l'équipe AfroNova.",
    ac_cta_btn: "Contacter AfroNova", ac_cta_btn2: "Site officiel de l'événement",
  },
  pt: {
    nav_home: "Início", nav_about: "Sobre Nós", nav_services: "Serviços",
    nav_portfolio: "Portfólio", nav_news: "Notícias", nav_partners: "Parceiros",
    nav_portal: "Portal de Expositores", nav_contact: "Contacto",
    hero_badge: "Pan-Africano · Eventos · Media · Inovação · Promoção",
    hero_sub1: "Não apenas organizamos eventos,",
    hero_sub2: "acendemos movimentos.",
    hero_body: "A AfroNova é uma empresa pan-africana de referência dedicada a celebrar, amplificar e promover o património cultural, a inovação e a excelência criativa de África. Sede em Adis Abeba, a operar em 50+ países.",
    hero_cta_discover: "Descobrir a AfroNova",
    hero_cta_services: "Os nossos serviços",
    hero_cta_work: "Trabalhar connosco",
    countdown_badge: "6.ª Edição · Evento principal",
    countdown_title1: "Africa", countdown_title2: "Celebrates", countdown_title3: "2026",
    countdown_theme: "\"Uma África, Um Povo: Unindo Cultura, Inovação e Empresa para um Futuro Próspero Comum\"",
    countdown_date: "10 to 15 de novembro de 2026",
    countdown_venue: "Sede da UA & UNECA, Adis Abeba",
    countdown_label: "Contagem decrescente para o evento",
    countdown_visit: "Visitar o site oficial",
    countdown_details: "Detalhes completos do evento",
    stat1_label: "Países alcançados", stat2_label: "Pilares de serviço",
    stat3_label: "Parceiros estratégicos", stat4_label: "Vidas impactadas anualmente",
    who_eyebrow: "Quem somos", who_title: "Uma força transformadora", who_highlight: "para África",
    who_body1: "A AfroNova atua como uma força transformadora, organizando experiências de ponta a ponta que capacitam comunidades, ligam culturas e posicionam narrativas africanas autênticas na vanguarda global.",
    who_body2: "De eventos de grande impacto a narrativas multimédia cativantes, a AfroNova é mais do que um prestador, é um movimento que remodela a forma como África é vista, ouvida e lembrada. Parceiro local oficial de",
    who_partner: "Legendary Gold Limited",
    who_story: "A nossa história",
    who_mission_label: "Missão",
    who_mission: "Amplificar as vozes africanas, promover o orgulho cultural e impulsionar uma mudança significativa através de eventos de classe mundial, multimédia inovador e comunicações estratégicas.",
    who_vision_label: "Visão",
    who_vision: "Tornar-se o principal hub de eventos e media de África, uma plataforma de confiança onde as culturas convergem e as histórias africanas autênticas moldam perspetivas globais.",
    who_location: "Adis Abeba, Etiópia",
    who_location_desc: "A capital diplomática de África, a passos da União Africana.",
    services_eyebrow: "O que fazemos", services_title: "Cinco pilares da", services_highlight: "excelência pan-africana",
    services_desc: "Capacidades de ponta a ponta em eventos, media, publicidade, publicação e merchandising de marca.",
    services_all: "Todos os serviços", services_learn: "Saber mais",
    why_eyebrow: "Porquê a AfroNova", why_title: "O que nos distingue", why_highlight: "",
    work_eyebrow: "Trabalho em destaque", work_title: "Projetos que nos", work_highlight: "definem",
    work_desc: "Um instantâneo do trabalho entregue pela AfroNova em todo o continente.",
    work_portfolio: "Portfólio completo", work_view: "Ver projeto", work_flagship: "Principal",
    partners_label: "Parceiros e colaboradores de confiança",
    cta_eyebrow: "Trabalhe connosco", cta_title: "Vamos construir algo", cta_highlight: "extraordinário",
    cta_body: "Se precisa de um evento de classe mundial, um documentário cativante, uma campanha pan-africana ou um projeto editorial, a AfroNova entrega.",
    cta_start: "Iniciar uma conversa", cta_explore: "Explorar serviços",
    footer_tagline: "Branding a Nova África. Possibilidades Ilimitadas. Não apenas organizamos eventos, acendemos movimentos.",
    footer_rights: "© 2026 AfroNova. Pan-Africano · Eventos · Media · Inovação · Promoção. Todos os direitos reservados.",
    footer_stay: "Mantenha-se atualizado", footer_stay_desc: "Receba as últimas notícias, atualizações de eventos e anúncios exclusivos.",
    footer_subscribe: "Subscrever", footer_subscribed: "Está na lista. Bem-vindo à AfroNova!",
    footer_company: "Empresa", footer_event: "Evento",
    cat_institutional: "Institucional", cat_strategic: "Estratégico", cat_diplomatic: "Diplomático",
    cat_corporate: "Corporativo", cat_media: "Media", cat_cultural: "Cultural",
    cat_hospitality: "Hospitalidade", cat_government: "Governo",
    news_cat_all: "Tudo", news_cat_event: "Evento", news_cat_partner: "Parceria",
    news_cat_exhibitors: "Expositores", news_cat_business: "Negócios",
    news_cat_recap: "Resumo", news_cat_production: "Produção",
    ac_h1_title: "Gala Moda & Prémios",     ac_h1_desc: "Espetáculos culturais, dança tradicional e cerimónia de prémios celebrando a excelência pan-africana.",
    ac_h2_title: "Fóruns de Negócios",       ac_h2_desc: "Discussões de alto nível sobre negócios, tecnologia e investimento intra-africanos.",
    ac_h3_title: "Exposição 40+ Nações",     ac_h3_desc: "Artesãos, vendedores e equipas corporativas de todo o continente africano.",
    ac_h4_title: "Participação Diáspora",    ac_h4_desc: "Conectar a diáspora africana a oportunidades, cultura e comunidade continentais.",
    ac_h5_title: "Vitrine Cultural",         ac_h5_desc: "Moda, artes visuais, cinema, música e espetáculos tradicionais representando o continente.",
    ac_h6_title: "Prémios Pan-Africanos",    ac_h6_desc: "Reconhecer indivíduos, empresas e instituições excepcionais que impulsionam o progresso africano.",
    prog1_title: "Cerimónia de Abertura", prog2_title: "Dia de Negócios 1", prog3_title: "Dia de Negócios 2",
    prog4_title: "Dia Cultura & Artes", prog5_title: "Gala de Prémios", prog6_title: "Cerimónia de Encerramento",
    tier1_name: "Patrocinador Título", tier2_name: "Patrocinador Ouro", tier3_name: "Patrocinador Prata",
    partners_all: "Todos",
    ed5: "5.ª Edição", ed4: "4.ª Edição", ed3: "3.ª Edição", ed2: "2.ª Edição", ed1: "1.ª Edição",
    svc1_full_desc: "De festivais culturais a cimeiras de negócios, a AfroNova entrega experiências de eventos completas.",
    svc1_f1: "Festivais culturais, fóruns de negócios e eventos alinhados com a UA",
    svc1_f2: "Design de eventos, gestão logística e segurança",
    svc1_f3: "Gestão de convidados de alto perfil e serviços de protocolo",
    svc1_f4: "Experiências híbridas com integração VR/AR",
    svc1_f5: "Criação de conteúdo legado e documentação pós-evento",
    svc1_cta: "Planeie o seu evento",
    svc2_title: "Produção multimédia", svc2_desc: "Documentários 4K, podcasts, cobertura broadcast e conteúdo de marca.",
    svc2_full_desc: "Storytelling cinematográfico e culturalmente enraizado que posiciona as narrativas africanas no centro do palco mundial.",
    svc2_f1: "Desenvolvimento de documentários e podcasts",
    svc2_f2: "Vídeo de qualidade 4K & Dolby, distribuição TV e curtas",
    svc2_f3: "Cobertura de eventos, vídeos musicais e séries de marca",
    svc2_f4: "Conteúdo cultural e comercial por criativos africanos",
    svc2_f5: "Produção broadcast ao vivo e streaming",
    svc2_cta: "Iniciar um projeto",
    svc3_title: "Publicidade estratégica", svc3_desc: "Campanhas em 10+ idiomas e gestão de redes sociais.",
    svc3_full_desc: "Campanhas de marca pan-africanas que ressoam em culturas, idiomas e fronteiras.",
    svc3_f1: "Campanhas digitais geo-segmentadas em 10+ idiomas",
    svc3_f2: "Criação de conteúdo multilingue e culturalmente localizado",
    svc3_f3: "Gestão de redes sociais e análise de audiência com IA",
    svc3_f4: "Brochuras AR, campanhas exteriores e colateral impresso",
    svc3_f5: "Ativação de patrocínio e posicionamento estratégico",
    svc3_cta: "Lançar uma campanha",
    svc4_title: "Impressão e merchandising", svc4_desc: "Brochuras, sinalização, vestuário e lembranças personalizadas.",
    svc4_full_desc: "Pontos de contacto físicos premium com a estética AfroNova, culturalmente enraizados e sustentáveis.",
    svc4_f1: "Brochuras, programas, sinalização e kits de evento",
    svc4_f2: "Merchandise de marca: vestuário, acessórios e lembranças",
    svc4_f3: "Estética de design pan-africano e materiais sustentáveis",
    svc4_f4: "Pacotes de presentes corporativos e colateral VIP",
    svc4_cta: "Obter orçamento",
    svc5_title: "Publicação e media digital", svc5_desc: "Revistas digitais, livros e narrativas de marca.",
    svc5_full_desc: "Conteúdo de marca que informa, inspira e perdura, de revistas digitais a livros sobre a cultura africana.",
    svc5_f1: "Edições de revistas digitais co-marcadas e antologias",
    svc5_f2: "Projetos de publicação e editoriais patrocinados",
    svc5_f3: "Storytelling de marca para parceiros corporativos e culturais",
    svc5_f4: "Estratégia de conteúdo para redes sociais e publicação digital",
    svc5_cta: "Começar a publicar",
    why1_title: "Alcance pan-africano", why1_desc: "Rede de 5.000+ líderes; presença em 50+ países.",
    why2_title: "Integridade cultural", why2_desc: "Visão africana com execução local, não impomos, amplificamos.",
    why3_title: "Inovação", why3_desc: "Integração AR/VR, análises de IA e storytelling digital de ponta.",
    why4_title: "Impacto mensurável", why4_desc: "500K+ impressões nos media; taxa de retenção de patrocinadores 70%+.",
    fw1_title: "Africa Celebrates 2025", fw1_type: "Evento principal", fw1_desc: "Parceiro principal na Etiópia, 20+ fóruns, 5.000+ participantes.",
    fw2_title: "AFRIMA 2025", fw2_type: "Conferência musical", fw2_desc: "Facilitação completa e posicionamento de marca pan-africano.",
    fw3_title: "Campanha Turismo Etiópia", fw3_type: "Publicidade", fw3_desc: "Campanha atingindo 15M+ espectadores.",
    tag_events: "Eventos", tag_media: "Media", tag_advertising: "Publicidade", tag_publishing: "Publicação", tag_merch: "Merchandising",
    about_eyebrow: "Sobre a AfroNova", about_h1: "Branding a Nova África.", about_h1b: "Possibilidades Ilimitadas.",
    about_hero_body: "A AfroNova é uma empresa pan-africana de referência dedicada a celebrar e promover o património cultural de África. Somos mais do que um prestador, somos um movimento.",
    about_who_eyebrow: "Quem somos", about_who_title: "Uma força transformadora", about_who_highlight: "para África",
    about_p1: "A AfroNova organiza experiências de ponta a ponta que capacitam comunidades e posicionam narrativas africanas autênticas na vanguarda global.",
    about_p2: "A operar em 50+ países com sede em Adis Abeba, servimos governos, empresas e comunidades.",
    about_p3: "Como parceiro local oficial de", about_p3b: ", trazemos alcance e investimento globais.",
    about_our_services: "Os nossos serviços",
    about_countries: "Países", about_reached: "alcançados",
    about_mission_h: "A nossa missão", about_mission_body: "Amplificar as vozes africanas e impulsionar uma mudança significativa.",
    about_vision_h: "A nossa visão", about_vision_body: "Tornar-se o principal hub de eventos e media de África.",
    about_partnership_badge: "Parceria estratégica", about_partnership_h: "Parceiro local oficial de",
    about_partnership_body: "A nossa parceria com a Legendary Gold Limited traz investimento internacional e experiência de classe mundial a cada projeto AfroNova.",
    about_values_eyebrow: "O que nos motiva", about_values_title: "Valores organizacionais", about_values_highlight: "fundamentais",
    about_lead_eyebrow: "Liderança", about_lead_title: "A pessoa por trás da", about_lead_highlight: "AfroNova",
    about_net_eyebrow: "A nossa rede", about_net_title: "Parceiros de", about_net_highlight: "confiança",
    about_view_partners: "Ver todos os parceiros",
    val1_title: "Profissionalismo", val1_desc: "Padrões de classe mundial em cada projeto.",
    val2_title: "Respeito e integridade", val2_desc: "Honesto, ético e culturalmente sensível.",
    val3_title: "Criatividade", val3_desc: "Pensamento audacioso e inovador.",
    val4_title: "Colaboração", val4_desc: "Construir pontes entre fronteiras.",
    val5_title: "Inclusividade", val5_desc: "Cada voz africana importa.",
    val6_title: "Foco no impacto", val6_desc: "O sucesso medido pela mudança real.",
    val7_title: "Orgulho cultural", val7_desc: "O património africano é o nosso ponto central.",
    val8_title: "Aprendizagem contínua", val8_desc: "Sempre a evoluir para melhor servir África.",
    svc_eyebrow: "O que fazemos", svc_h1: "Cinco pilares da", svc_h1b: "excelência pan-africana",
    svc_hero_body: "Da gestão de eventos à produção multimédia, publicidade, merchandising e publicação, a AfroNova entrega.",
    svc_process_eyebrow: "Como trabalhamos", svc_process_title: "O nosso processo",
    svc_cta_h: "Vamos construir algo", svc_cta_hb: "extraordinário juntos.",
    svc_cta_body: "Fale-nos do seu projeto, preparamos uma proposta em 48 horas.",
    svc_cta_btn: "Obter uma proposta",
    proc1_title: "Descoberta", proc1_desc: "Ouvimos, pesquisamos e compreendemos os seus objetivos.",
    proc2_title: "Estratégia", proc2_desc: "Plano personalizado com prazos, orçamentos e KPIs.",
    proc3_title: "Produção", proc3_desc: "As nossas equipas executam com precisão e excelência criativa.",
    proc4_title: "Entrega", proc4_desc: "A tempo, dentro do orçamento, com relatório completo.",
    contact_eyebrow: "Vamos falar", contact_h1: "Entrar em", contact_h1b: "contacto",
    contact_hero_body: "Se está a planear um evento, produzir conteúdo, lançar uma campanha ou simplesmente quer saber mais sobre a AfroNova, adoraríamos ouvir de si.",
    contact_office: "Sede", contact_phone: "Telefone", contact_hours: "Horário de funcionamento",
    contact_hours_val: "Segunda  to  Sexta · 9h00  to  17h00 (HEA)",
    contact_follow: "Siga-nos",
    contact_direct: "Contacto direto",
    contact_form_eyebrow: "Enviar mensagem", contact_form_title: "Estamos aqui", contact_form_highlight: "para si",
    contact_send: "Enviar mensagem",
    contact_map: "Encontre-nos, Africa Avenue, Adis Abeba",
    contact_success: "A sua mensagem foi recebida. Responderemos em 1 to 2 dias úteis.",
    contact_field_name: "Nome completo", contact_field_name_ph: "O seu nome completo",
    contact_field_email: "Endereço de e-mail",
    contact_field_phone: "Número de telefone", contact_field_phone_ph: "+1 234 567 8900",
    contact_field_inquiry: "Tipo de consulta",
    contact_field_msg: "Mensagem", contact_field_msg_ph: "Fale-nos do seu projeto...",
    contact_inquiry_general: "Consulta geral", contact_inquiry_event: "Gestão de eventos",
    contact_inquiry_media: "Produção multimédia", contact_inquiry_ads: "Publicidade / Campanhas",
    contact_inquiry_ac: "Africa Celebrates 2026", contact_inquiry_sponsor: "Patrocínio",
    contact_inquiry_press: "Media / Imprensa", contact_inquiry_other: "Outro",
    partners_eyebrow: "A nossa rede", partners_h1: "Parceiros de", partners_h1b: "confiança",
    partners_hero_body: "A AfroNova trabalha com governos, missões diplomáticas e instituições culturais em 50+ países. Passe o rato por qualquer cartão para saber mais.",
    partners_stat1: "Parceiros ativos", partners_stat2: "Países cobertos",
    partners_stat3: "Categorias de parceiros", partners_stat4: "Anos de colaboração",
    partners_hover: "Passe o rato para saber mais",
    partners_cta_badge: "Oportunidades de parceria",
    partners_cta_h: "Torne-se um", partners_cta_hb: "parceiro",
    partners_cta_body: "Junte-se à rede crescente da AfroNova de instituições que moldam o futuro da cultura pan-africana.",
    partners_cta_btn: "Contacte-nos", partners_about_btn: "Saiba mais sobre a AfroNova",
    portfolio_eyebrow: "O nosso trabalho", portfolio_h1: "Portfólio &", portfolio_h1b: "projetos em destaque",
    portfolio_hero_body: "De Africa Celebrates à AFRIMA até produções multimédia, prova de que acendemos movimentos.",
    portfolio_featured_eyebrow: "Trabalho em destaque", portfolio_featured_title: "Projetos", portfolio_featured_highlight: "principais",
    portfolio_editions_eyebrow: "Africa Celebrates", portfolio_editions_title: "Edições", portfolio_editions_highlight: "passadas",
    portfolio_gallery_eyebrow: "Galeria", portfolio_gallery_title: "Momentos de", portfolio_gallery_highlight: "excelência",
    portfolio_media_eyebrow: "Estudos de caso", portfolio_media_title: "Projetos media &", portfolio_media_highlight: "produção",
    portfolio_attendees: "Participantes", portfolio_nations: "Nações",
    news_eyebrow: "Últimas atualizações", news_h1: "Notícias &", news_h1b: "Imprensa",
    news_hero_body: "Comunicados de imprensa, atualizações de eventos, parcerias e histórias do mundo AfroNova.",
    news_featured: "Destaque", news_read: "Ler",
    ac_badge: "6.ª Edição · Festival pan-africano",
    ac_theme: "\"Uma África, Um Povo: Unindo Cultura, Inovação e Empresa para um Futuro Próspero Comum\"",
    ac_date: "10 to 15 de novembro de 2026", ac_venue: "Sede UA & UNECA, Adis Abeba", ac_nations: "40+ nações africanas",
    ac_countdown_label: "Contagem decrescente para Africa Celebrates 2026",
    ac_visit: "Visitar o site oficial", ac_download: "Descarregar programa",
    ac_highlights_eyebrow: "O que esperar", ac_highlights_title: "Destaques do", ac_highlights_highlight: "programa",
    ac_schedule_eyebrow: "6 dias de excelência", ac_schedule_title: "Programa do", ac_schedule_highlight: "evento",
    ac_schedule_pdf: "Descarregar PDF completo",
    ac_venues_eyebrow: "Locais", ac_venues_title: "O coração de", ac_venues_highlight: "Adis Abeba",
    ac_venue1_badge: "Local principal", ac_venue2_badge: "Local parceiro",
    ac_venue1_name: "Sede da União Africana",
    ac_venue1_desc: "O lar emblemático da diplomacia pan-africana, um símbolo de unidade continental.",
    ac_venue2_name: "UNECA, Comissão Económica das Nações Unidas para África",
    ac_venue2_desc: "A principal instituição económica de África, cenário ideal para fóruns de inovação.",
    ac_sponsor_eyebrow: "Parceria connosco", ac_sponsor_title: "Oportunidades de", ac_sponsor_highlight: "patrocínio",
    ac_sponsor_desc: "Posicione a sua marca no centro do festival pan-africano mais celebrado.",
    ac_sponsor_cta: "Contacte-nos",
    ac_cta_eyebrow: "Interessado?", ac_cta_title: "Participe em", ac_cta_highlight: "Africa Celebrates",
    ac_cta_body: "Se está interessado em patrocínio, parcerias de media ou assistir ao evento, contacte diretamente a equipa AfroNova.",
    ac_cta_btn: "Contactar AfroNova", ac_cta_btn2: "Site oficial do evento",
  },
  ar: {
    nav_home: "الرئيسية", nav_about: "من نحن", nav_services: "الخدمات",
    nav_portfolio: "المحفظة", nav_news: "الأخبار", nav_partners: "الشركاء",
    nav_portal: "بوابة العارضين", nav_contact: "اتصل بنا",
    hero_badge: "أفريقي شامل · فعاليات · إعلام · ابتكار · ترويج",
    hero_sub1: "نحن لا نستضيف الفعاليات فحسب,",
    hero_sub2: "نحن نُشعل الحركات.",
    hero_body: "أفرونوفا هي مؤسسة أفريقية شاملة رائدة مكرّسة للاحتفاء بالتراث الثقافي الأفريقي وتضخيمه وترويجه. المقر الرئيسي في أديس أبابا، تعمل في أكثر من 50 دولة.",
    hero_cta_discover: "اكتشف أفرونوفا",
    hero_cta_services: "خدماتنا",
    hero_cta_work: "اعمل معنا",
    countdown_badge: "الطبعة السادسة · الحدث الرئيسي",
    countdown_title1: "أفريقيا", countdown_title2: "تحتفل", countdown_title3: "2026",
    countdown_theme: "\"أفريقيا واحدة، شعب واحد: توحيد الثقافة والابتكار والمؤسسات من أجل مستقبل مزدهر مشترك\"",
    countdown_date: "10 to 15 نوفمبر 2026",
    countdown_venue: "مقر الاتحاد الأفريقي و UNECA، أديس أبابا",
    countdown_label: "العد التنازلي للحدث",
    countdown_visit: "زيارة الموقع الرسمي",
    countdown_details: "تفاصيل الحدث الكاملة",
    stat1_label: "الدول المُشمولة", stat2_label: "ركائز الخدمة الأساسية",
    stat3_label: "الشركاء الاستراتيجيون", stat4_label: "الأرواح المُؤثَّر فيها سنوياً",
    who_eyebrow: "من نحن", who_title: "قوة تحويلية", who_highlight: "لأفريقيا",
    who_body1: "تعمل أفرونوفا كقوة تحويلية، تنسّق تجارب شاملة تُمكّن المجتمعات وتجسر الثقافات وتضع الروايات الأفريقية الأصيلة في مقدمة المسرح العالمي.",
    who_body2: "من الفعاليات عالية التأثير إلى السرد الإعلامي المقنع، أفرونوفا أكثر من مجرد مزود خدمة, إنها حركة تُعيد تشكيل كيف تُرى أفريقيا وتُسمع وتُتذكر. الشريك المحلي الرسمي لـ",
    who_partner: "ليجنداري غولد ليميتد",
    who_story: "قصتنا",
    who_mission_label: "المهمة",
    who_mission: "تضخيم الأصوات الأفريقية وتعزيز الفخر الثقافي وإحداث تغيير ذي معنى من خلال فعاليات عالمية المستوى وإعلام مبتكر وتواصل استراتيجي.",
    who_vision_label: "الرؤية",
    who_vision: "أن نصبح المحور الرائد للفعاليات والإعلام في أفريقيا, منصة موثوقة تتقاطع فيها الثقافات وتُشكّل القصص الأفريقية الأصيلة المنظورات العالمية.",
    who_location: "أديس أبابا، إثيوبيا",
    who_location_desc: "العاصمة الدبلوماسية لأفريقيا، على مقربة من الاتحاد الأفريقي.",
    services_eyebrow: "ما نفعله", services_title: "خمس ركائز", services_highlight: "للتميز الأفريقي الشامل",
    services_desc: "قدرات شاملة عبر الفعاليات والإعلام والإعلانات والنشر وترويج العلامات التجارية.",
    services_all: "جميع الخدمات", services_learn: "اعرف المزيد",
    why_eyebrow: "لماذا أفرونوفا", why_title: "ما الذي يُميّزنا", why_highlight: "",
    work_eyebrow: "أعمال مميزة", work_title: "مشاريع تُعرّفنا", work_highlight: "",
    work_desc: "لمحة عن الأعمال التي قدّمتها أفرونوفا عبر القارة.",
    work_portfolio: "المحفظة الكاملة", work_view: "عرض المشروع", work_flagship: "الرئيسي",
    partners_label: "شركاء وتعاونيون موثوق بهم",
    cta_eyebrow: "اعمل معنا", cta_title: "لنبنِ شيئاً", cta_highlight: "استثنائياً",
    cta_body: "سواء احتجت إلى فعالية عالمية المستوى، فيلم وثائقي، حملة أفريقية شاملة، أو مشروع نشر, أفرونوفا تُنجز.",
    cta_start: "ابدأ محادثة", cta_explore: "استكشف الخدمات",
    footer_tagline: "بناء أفريقيا الجديدة. إمكانيات لا محدودة. نحن لا نستضيف الفعاليات فحسب, نحن نُشعل الحركات.",
    footer_rights: "© 2026 أفرونوفا. أفريقي شامل · فعاليات · إعلام · ابتكار · ترويج. جميع الحقوق محفوظة.",
    footer_stay: "ابقَ على اطلاع", footer_stay_desc: "احصل على آخر الأخبار وتحديثات الفعاليات والإعلانات الحصرية.",
    footer_subscribe: "اشترك", footer_subscribed: "أنت في القائمة. مرحباً بك في أفرونوفا!",
    footer_company: "الشركة", footer_event: "الحدث",
    cat_institutional: "مؤسسي", cat_strategic: "استراتيجي", cat_diplomatic: "دبلوماسي",
    cat_corporate: "شركات", cat_media: "إعلام", cat_cultural: "ثقافي",
    cat_hospitality: "ضيافة", cat_government: "حكومي",
    news_cat_all: "الكل", news_cat_event: "فعالية", news_cat_partner: "شراكة",
    news_cat_exhibitors: "العارضون", news_cat_business: "الأعمال",
    news_cat_recap: "ملخص", news_cat_production: "إنتاج",
    ac_h1_title: "ليلة الأزياء والجوائز",   ac_h1_desc: "عروض ثقافية ورقص تقليدي وحفل توزيع جوائز يحتفل بالتميز الأفريقي الشامل.",
    ac_h2_title: "منتديات الأعمال والتجارة", ac_h2_desc: "نقاشات رفيعة المستوى حول الأعمال والتكنولوجيا والاستثمار داخل أفريقيا.",
    ac_h3_title: "معرض 40+ دولة",            ac_h3_desc: "حرفيون وبائعون وفرق من القارة الأفريقية والشتات العالمي.",
    ac_h4_title: "مشاركة الشتات",            ac_h4_desc: "ربط الشتات الأفريقي بالفرص والثقافة والمجتمع القاري.",
    ac_h5_title: "عرض ثقافي",                ac_h5_desc: "موضة وفنون بصرية وأفلام وموسيقى وعروض تقليدية.",
    ac_h6_title: "جوائز أفريقية شاملة",      ac_h6_desc: "تكريم الأفراد والمؤسسات المتميزة التي تدفع التقدم الأفريقي.",
    prog1_title: "حفل الافتتاح", prog2_title: "يوم الأعمال 1", prog3_title: "يوم الأعمال 2",
    prog4_title: "يوم الثقافة والفنون", prog5_title: "ليلة الجوائز الكبرى", prog6_title: "حفل الختام",
    tier1_name: "الراعي الرئيسي", tier2_name: "الراعي الذهبي", tier3_name: "الراعي الفضي",
    partners_all: "الكل",
    ed5: "الطبعة الخامسة", ed4: "الطبعة الرابعة", ed3: "الطبعة الثالثة", ed2: "الطبعة الثانية", ed1: "الطبعة الأولى",
    svc1_full_desc: "من المهرجانات الثقافية إلى قمم الأعمال، تقدم أفرونوفا تجارب فعاليات متكاملة.",
    svc1_f1: "مهرجانات ثقافية ومنتديات أعمال وفعاليات الاتحاد الأفريقي",
    svc1_f2: "تصميم الفعاليات وإدارة اللوجستيات والأمن",
    svc1_f3: "إدارة الضيوف البارزين وخدمات البروتوكول",
    svc1_f4: "تجارب هجينة مع تكامل VR/AR",
    svc1_f5: "إنشاء محتوى الإرث وتوثيق ما بعد الفعالية",
    svc1_cta: "خطط لفعاليتك",
    svc2_title: "الإنتاج الإعلامي", svc2_desc: "وثائقيات 4K وبودكاست وبث مباشر ومحتوى علامات تجارية.",
    svc2_full_desc: "سرد سينمائي متجذر ثقافياً يضع الروايات الأفريقية في مقدمة المسرح العالمي.",
    svc2_f1: "تطوير الأفلام الوثائقية والبودكاست",
    svc2_f2: "فيديو 4K وDolby وتوزيع تلفزيوني وأفلام قصيرة",
    svc2_f3: "تغطية الفعاليات ومقاطع الموسيقى والمسلسلات",
    svc2_f4: "محتوى ثقافي وتجاري من مبدعين أفارقة",
    svc2_f5: "إنتاج بث مباشر متعدد الكاميرات والبث المباشر",
    svc2_cta: "ابدأ مشروعاً",
    svc3_title: "الإعلان الاستراتيجي", svc3_desc: "حملات بأكثر من 10 لغات وإدارة وسائل التواصل الاجتماعي.",
    svc3_full_desc: "حملات علامات تجارية أفريقية شاملة تتردد صداها عبر الثقافات واللغات والحدود.",
    svc3_f1: "حملات رقمية مستهدفة جغرافياً بأكثر من 10 لغات",
    svc3_f2: "إنشاء محتوى متعدد اللغات ومحلي ثقافياً",
    svc3_f3: "إدارة وسائل التواصل الاجتماعي وتحليلات الجمهور بالذكاء الاصطناعي",
    svc3_f4: "كتيبات AR وحملات خارجية وضمانات مطبوعة",
    svc3_f5: "تفعيل الرعاية والتموضع الاستراتيجي للعلامة التجارية",
    svc3_cta: "إطلاق حملة",
    svc4_title: "الطباعة والبضائع الترويجية", svc4_desc: "كتيبات ولافتات وملابس وهدايا مخصصة.",
    svc4_full_desc: "نقاط تواصل مادية متميزة بجمالية أفرونوفا, متجذرة ثقافياً ومستدامة.",
    svc4_f1: "كتيبات وبرامج ولافتات وحقائب الفعاليات",
    svc4_f2: "بضائع ذات علامة تجارية: ملابس وإكسسوارات وتذكارات",
    svc4_f3: "جماليات التصميم الأفريقي الشامل والمواد المستدامة",
    svc4_f4: "حقائب الهدايا المؤسسية وضمانات VIP",
    svc4_cta: "احصل على عرض سعر",
    svc5_title: "النشر والإعلام الرقمي", svc5_desc: "مجلات رقمية وكتب وسرد للعلامات التجارية.",
    svc5_full_desc: "محتوى العلامة التجارية الذي يُعلم ويلهم ويدوم, من المجلات الرقمية إلى كتب الثقافة الأفريقية.",
    svc5_f1: "إصدارات مجلات رقمية مشتركة العلامة وأنطولوجيات",
    svc5_f2: "مشاريع نشر وتحريرات مدعومة",
    svc5_f3: "سرد العلامة التجارية للشركاء المؤسسيين والثقافيين",
    svc5_f4: "استراتيجية محتوى وسائل التواصل الاجتماعي والنشر الرقمي",
    svc5_cta: "ابدأ النشر",
    why1_title: "الوصول الأفريقي الشامل", why1_desc: "شبكة من 5,000+ قائد؛ حضور في أكثر من 50 دولة.",
    why2_title: "النزاهة الثقافية", why2_desc: "رؤية أفريقية بتنفيذ محلي, لا نفرض، بل نضخّم.",
    why3_title: "الابتكار", why3_desc: "تكامل AR/VR وتحليلات الذكاء الاصطناعي وسرد رقمي متطور.",
    why4_title: "تأثير قابل للقياس", why4_desc: "أكثر من 500 ألف انطباع إعلامي؛ معدل احتفاظ بالرعاة 70%+.",
    fw1_title: "أفريقيا تحتفل 2025", fw1_type: "الحدث الرئيسي", fw1_desc: "شريك التنفيذ الرئيسي في إثيوبيا, 20+ منتدى، 5,000+ مشارك.",
    fw2_title: "AFRIMA 2025", fw2_type: "مؤتمر موسيقي", fw2_desc: "تيسير كامل للفعالية وتحديد موقع العلامة التجارية.",
    fw3_title: "حملة السياحة الإثيوبية", fw3_type: "إعلان", fw3_desc: "حملة وصلت إلى 15 مليون مشاهد.",
    tag_events: "فعاليات", tag_media: "إعلام", tag_advertising: "إعلانات", tag_publishing: "نشر", tag_merch: "بضائع",
    about_eyebrow: "عن أفرونوفا", about_h1: "بناء أفريقيا الجديدة.", about_h1b: "إمكانيات لا محدودة.",
    about_hero_body: "أفرونوفا مؤسسة أفريقية شاملة رائدة مكرّسة للاحتفاء بالتراث الثقافي الأفريقي. نحن أكثر من مجرد مزود, نحن حركة.",
    about_who_eyebrow: "من نحن", about_who_title: "قوة تحويلية", about_who_highlight: "لأفريقيا",
    about_p1: "تعمل أفرونوفا على تنسيق تجارب شاملة تُمكّن المجتمعات وتضع الروايات الأفريقية في الصدارة.",
    about_p2: "تعمل في أكثر من 50 دولة مع مقر في أديس أبابا، نخدم الحكومات والشركات والمجتمعات.",
    about_p3: "بوصفنا الشريك المحلي الرسمي لـ", about_p3b: "، نجلب الوصول والاستثمار العالميين.",
    about_our_services: "خدماتنا",
    about_countries: "دولة", about_reached: "مُشمولة",
    about_mission_h: "مهمتنا", about_mission_body: "تضخيم الأصوات الأفريقية وإحداث تغيير ذي معنى.",
    about_vision_h: "رؤيتنا", about_vision_body: "أن نصبح المحور الرائد للفعاليات والإعلام في أفريقيا.",
    about_partnership_badge: "شراكة استراتيجية", about_partnership_h: "الشريك المحلي الرسمي لـ",
    about_partnership_body: "تجلب شراكتنا مع ليجنداري غولد ليميتد استثمارات دولية وخبرة عالمية المستوى لكل مشروع.",
    about_values_eyebrow: "ما يحرّكنا", about_values_title: "القيم التنظيمية", about_values_highlight: "الأساسية",
    about_lead_eyebrow: "القيادة", about_lead_title: "الشخص وراء", about_lead_highlight: "أفرونوفا",
    about_net_eyebrow: "شبكتنا", about_net_title: "شركاء", about_net_highlight: "موثوقون",
    about_view_partners: "عرض جميع الشركاء",
    val1_title: "الاحترافية", val1_desc: "معايير عالمية في كل مشروع وفعالية.",
    val2_title: "الاحترام والنزاهة", val2_desc: "صادق وأخلاقي وحساس ثقافياً.",
    val3_title: "الإبداع", val3_desc: "تفكير جريء ومبتكر.",
    val4_title: "التعاون", val4_desc: "بناء الجسور عبر الحدود والمجتمعات.",
    val5_title: "الشمولية", val5_desc: "كل صوت أفريقي مهم.",
    val6_title: "التركيز على التأثير", val6_desc: "يُقاس النجاح بالتغيير الحقيقي.",
    val7_title: "الفخر الثقافي", val7_desc: "التراث الأفريقي هو محور كل ما نفعله.",
    val8_title: "التعلم المستمر", val8_desc: "دائماً نتطور لخدمة أفريقيا بشكل أفضل.",
    svc_eyebrow: "ما نفعله", svc_h1: "خمس ركائز", svc_h1b: "للتميز الأفريقي الشامل",
    svc_hero_body: "من إدارة الفعاليات إلى الإنتاج الإعلامي والإعلانات والترويج والنشر, أفرونوفا تُنجز.",
    svc_process_eyebrow: "كيف نعمل", svc_process_title: "عمليتنا",
    svc_cta_h: "لنبنِ شيئاً", svc_cta_hb: "استثنائياً معاً.",
    svc_cta_body: "أخبرنا عن مشروعك, سنعدّ اقتراحاً في غضون 48 ساعة.",
    svc_cta_btn: "احصل على اقتراح",
    proc1_title: "الاستكشاف", proc1_desc: "نستمع ونبحث ونفهم أهدافك بعمق.",
    proc2_title: "الاستراتيجية", proc2_desc: "خطة مخصصة مع جداول زمنية وميزانيات ومؤشرات قابلة للقياس.",
    proc3_title: "الإنتاج", proc3_desc: "فرقنا تُنفّذ بدقة وتميز إبداعي.",
    proc4_title: "التسليم", proc4_desc: "في الوقت المحدد وضمن الميزانية مع تقرير كامل.",
    contact_eyebrow: "لنتحدث", contact_h1: "تواصل", contact_h1b: "معنا",
    contact_hero_body: "سواء كنت تخطط لفعالية أو تنتج محتوى أو تطلق حملة أو تريد معرفة المزيد عن أفرونوفا, يسعدنا سماعك.",
    contact_office: "المقر الرئيسي", contact_phone: "الهاتف", contact_hours: "ساعات العمل",
    contact_hours_val: "الاثنين  to  الجمعة · 9:00 صباحاً  to  5:00 مساءً (توقيت شرق أفريقيا)",
    contact_follow: "تابعنا",
    contact_direct: "التواصل المباشر",
    contact_form_eyebrow: "أرسل رسالة", contact_form_title: "نحن هنا", contact_form_highlight: "من أجلك",
    contact_send: "إرسال الرسالة",
    contact_map: "ابحث عنا, شارع أفريقيا، أديس أبابا",
    contact_success: "تم استلام رسالتك. سنردّ عليك في غضون 1 to 2 يوم عمل.",
    contact_field_name: "الاسم الكامل", contact_field_name_ph: "اسمك الكامل",
    contact_field_email: "عنوان البريد الإلكتروني",
    contact_field_phone: "رقم الهاتف", contact_field_phone_ph: "+1 234 567 8900",
    contact_field_inquiry: "نوع الاستفسار",
    contact_field_msg: "الرسالة", contact_field_msg_ph: "أخبرنا عن مشروعك أو استفسارك...",
    contact_inquiry_general: "استفسار عام", contact_inquiry_event: "إدارة الفعاليات",
    contact_inquiry_media: "الإنتاج الإعلامي", contact_inquiry_ads: "الإعلانات / الحملات",
    contact_inquiry_ac: "أفريقيا تحتفل 2026", contact_inquiry_sponsor: "الرعاية",
    contact_inquiry_press: "الإعلام / الصحافة", contact_inquiry_other: "أخرى",
    partners_eyebrow: "شبكتنا", partners_h1: "شركاء", partners_h1b: "موثوقون",
    partners_hero_body: "تعمل أفرونوفا مع الحكومات والبعثات الدبلوماسية والمؤسسات الثقافية في أكثر من 50 دولة. مرّر الفأرة فوق أي بطاقة لمعرفة المزيد.",
    partners_stat1: "الشركاء النشطون", partners_stat2: "الدول المُشمولة",
    partners_stat3: "فئات الشركاء", partners_stat4: "سنوات التعاون",
    partners_hover: "مرّر للمعرفة المزيد",
    partners_cta_badge: "فرص الشراكة",
    partners_cta_h: "كن", partners_cta_hb: "شريكاً",
    partners_cta_body: "انضم إلى شبكة أفرونوفا المتنامية من المؤسسات التي تشكّل مستقبل الثقافة الأفريقية الشاملة.",
    partners_cta_btn: "تواصل معنا", partners_about_btn: "تعرّف على أفرونوفا",
    portfolio_eyebrow: "أعمالنا", portfolio_h1: "المحفظة &", portfolio_h1b: "المشاريع المميزة",
    portfolio_hero_body: "من أفريقيا تحتفل إلى AFRIMA والإنتاج الإعلامي, دليل على أننا نُشعل الحركات.",
    portfolio_featured_eyebrow: "أعمال مميزة", portfolio_featured_title: "مشاريع", portfolio_featured_highlight: "رئيسية",
    portfolio_editions_eyebrow: "أفريقيا تحتفل", portfolio_editions_title: "إصدارات", portfolio_editions_highlight: "سابقة",
    portfolio_gallery_eyebrow: "معرض الصور", portfolio_gallery_title: "لحظات", portfolio_gallery_highlight: "التميز",
    portfolio_media_eyebrow: "دراسات حالة", portfolio_media_title: "مشاريع الإعلام &", portfolio_media_highlight: "الإنتاج",
    portfolio_attendees: "المشاركون", portfolio_nations: "الدول",
    news_eyebrow: "آخر التحديثات", news_h1: "الأخبار &", news_h1b: "الصحافة",
    news_hero_body: "بيانات صحفية وتحديثات فعاليات وشراكات وقصص من عالم أفرونوفا.",
    news_featured: "مميز", news_read: "اقرأ",
    ac_badge: "الطبعة السادسة · مهرجان أفريقي شامل",
    ac_theme: "\"أفريقيا واحدة، شعب واحد: توحيد الثقافة والابتكار والمؤسسات من أجل مستقبل مزدهر مشترك\"",
    ac_date: "10 to 15 نوفمبر 2026", ac_venue: "مقر الاتحاد الأفريقي و UNECA، أديس أبابا", ac_nations: "أكثر من 40 دولة أفريقية",
    ac_countdown_label: "العد التنازلي لأفريقيا تحتفل 2026",
    ac_visit: "زيارة الموقع الرسمي", ac_download: "تنزيل البرنامج",
    ac_highlights_eyebrow: "ما يمكن توقعه", ac_highlights_title: "أبرز البرنامج", ac_highlights_highlight: "",
    ac_schedule_eyebrow: "6 أيام من التميز", ac_schedule_title: "برنامج", ac_schedule_highlight: "الفعالية",
    ac_schedule_pdf: "تنزيل ملف PDF الكامل",
    ac_venues_eyebrow: "أماكن الفعالية", ac_venues_title: "قلب", ac_venues_highlight: "أديس أبابا",
    ac_venue1_badge: "الموقع الرئيسي", ac_venue2_badge: "الموقع الشريك",
    ac_venue1_name: "مقر الاتحاد الأفريقي",
    ac_venue1_desc: "البيت الرمزي للدبلوماسية الأفريقية الشاملة, رمز الوحدة القارية.",
    ac_venue2_name: "UNECA, لجنة الأمم المتحدة الاقتصادية لأفريقيا",
    ac_venue2_desc: "المؤسسة الاقتصادية الرائدة في أفريقيا، المكان المثالي لمنتديات الأعمال والابتكار.",
    ac_sponsor_eyebrow: "شاركنا", ac_sponsor_title: "فرص", ac_sponsor_highlight: "الرعاية",
    ac_sponsor_desc: "ضع علامتك التجارية في قلب أكثر المهرجانات الأفريقية الشاملة احتفالاً.",
    ac_sponsor_cta: "تواصل معنا",
    ac_cta_eyebrow: "مهتم؟", ac_cta_title: "شارك في", ac_cta_highlight: "أفريقيا تحتفل",
    ac_cta_body: "سواء كنت مهتماً بالرعاية أو شراكات الإعلام أو حضور الفعالية, تواصل مع فريق أفرونوفا مباشرة.",
    ac_cta_btn: "تواصل مع أفرونوفا", ac_cta_btn2: "الموقع الرسمي للفعالية",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  locale: "en", setLocale: () => {}, t: (k) => k, isRTL: false,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");
  const isRTL = RTL_LOCALES.includes(locale);
  const setLocale = (l: Locale) => setLocaleState(l);

  useEffect(() => {
    const html = document.documentElement;
    html.setAttribute("lang", locale);
    html.setAttribute("dir", isRTL ? "rtl" : "ltr");
  }, [locale, isRTL]);

  const t = (key: string): string =>
    translations[locale][key] ?? translations["en"][key] ?? key;

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
